### ISSUE TITLE
Fix tracking calls for child pages

### ISSUE THREAD

**Issue by wdamien** [gskinner/regexr#100]
definitely some issues with our analytics implementation.
ex. /Character classes/Reference/undefined
and the order is different on different pages
ex. Reference /Character classes vs Character classes/Reference

**Comment by gskinner** [comment]
We will be reimplementing tracking for v3.0, lets aim to fix it there.

**Comment by gskinner** [comment]
Hopefully fixed in v3.0. Reopen if not.
