### ISSUE TITLE
Small issue with mutline

### ISSUE THREAD

**Issue by maxkorp** [gskinner/regexr#101]
Using the site, I'm not getting matches on subsequent lines with multiline enabled. 

Pattern: `^\d+\.\d+\.\d+$` (`/m` at the end enable via the checkbox). 

For example in cases one, `0.0.4` will match but `0.0.5` will not. In case two, the reverse is true. 
Input case 1: 
```
0.0.4
0.0.5
```

Input case 2: 
```
0.0.5

0.0.4
```
Both obviously match the pattern. Not a big deal just thought it would be worht pointing out. I'm guessing its something do do with the `^` char

**Comment by gskinner** [comment]
Hmm. For me that seems to match as expected.
http://regexr.com/3b5bk

For me, that example matches all but the last entry (as expected). If you're seeing something different with the link above, its likely an issue with the Regex engine in your browser. If so, could you let me know browser, version, and OS?

**Comment by maxkorp** [comment]
It's absolutely working for me now. Odd. I wonder if I maybe hit a JS error in the background somewhere or something. I hadn't tried refreshing the page. Thats the only thing I can think of :shrug:. 
Thanks anyways man!
