### ISSUE TITLE
with local installation: "the expression took longer than 250ms to execute" at 100k lines

### ISSUE THREAD

**Issue by maieko** [gskinner/regexr#102]
Hello,

i installed the application on my local computer. After pasting my text file with 100k relative short lines of text the program showed me the error message: "the expression took longer than 250ms to execute".  The test has been successfully pasted into the text-area but the substitution doesn't work. 
also nothing is marked even though it should match things. If i uncheck the global box the first line gets matched properly (blue background).

Is there some way to convert the text even though its large?

**Comment by wdamien** [comment]
@maieko the 250ms limit is in place to prevent cases where the RegExp can get into infinite loops and actually crash the browser, so I'm hesitant to increase the limit for cases like yours. For large find and replace situations I would recommend first using RegExr to validate your expression, then switch to using a code/text editor for the actual replace. Most of them have a Regular Expression option that should suit your situation.

**Comment by gskinner** [comment]
It might be interesting to look at including a bit of debug data with that error. For example, a % value indicating how far through the input the engine made it before giving up. Would at least give us an idea of where its giving up in cases like this.

**Comment by wdamien** [comment]
Since the regular expression is run in a Worker, it could be left running the background, then surface a "This expressions is taking a long time. Do you wish to cancel it?" dialog. Giving control to the end user for whether or not to cancel it.
