### ISSUE TITLE
Add a visualizer like Regulex

### ISSUE THREAD

**Issue by glebec** [gskinner/regexr#105]
I think it would be awesome if you could add a pattern visualizer like [Regulex](https://jex.im/regulex/). Currently when I work on regular expressions I keep both Regulex & Regexr open and copy-paste between windows… yuck. One site which handles reference, text demoing, _and_ pattern visualization would be the holy grail of regex tools.

**Comment by Nightfirecat** [comment]
Duplicate of #52.

**Comment by gskinner** [comment]
Closing in favor of #52
