### ISSUE TITLE
demo window (text)

### ISSUE THREAD

**Issue by marcoponta** [gskinner/regexr#106]
All text contained treated as one. First character is only the first one, and not the first of following text after an Enter, (see Rubular.com : any new line treated separetely)

**Comment by wdamien** [comment]
Could you post a screen capture with the issue your seeing? Thanks!

**Comment by marcoponta** [comment]
Attached pic as requested.
(I think) A quick direct reference as in rubular would be appreciated, also an implementation example ( mysqli: .... REGEXP '^[^a-z A-Z]' )

  ----- Original Message -----

**Comment by gskinner** [comment]
Your image didn't come through, but I think you may be looking for the `multiline` (m) flag:
http://regexr.com/3be8h

Feel free to reopen if that isn't the issue.

**Comment by marcoponta** [comment]
Done!
That's what was missing for me.
Thanks
  ----- Original Message -----
