### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by rdpascua** [gskinner/regexr#109]
Do you have any plans adding this?

**Comment by wdamien** [comment]
No we have not considered this. Can you provide more details on what you envision a Chrome extension doing?

**Comment by rdpascua** [comment]
Sorry what I mean is a standalone chrome application, in which you can run regexr offline

Like postman
https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

**Comment by Nightfirecat** [comment]
Duplicate of #26?

**Comment by gskinner** [comment]
Yes. Duplicate. Closing.
