### ISSUE TITLE
Error in site layout

### ISSUE THREAD

**Issue by mweitzman** [gskinner/regexr#112]
![image](https://cloud.githubusercontent.com/assets/8472961/10210645/e34cb7dc-67bf-11e5-9c96-6d1bfd480a71.png)

The layout is not working propperly in my PC nor in any other PC with a Linux distribution that I've seen, hope you can solve this, this is the best website I've used to test RegExp's, you've done a great job!

OS: Ubuntu 15.04 (64-bit)
Browser: Chrome 45.0.2454.101 (64-bit)

If I access from Firefox it works fine though, but I'd really like using regexr in Chrome since it's my default browser.

**Comment by alundiak** [comment]
I have the same. And reproduced recently. I mean, I have normal access to site at Oct-01, ~14:00 UTC+1, and now, 15:20 UTC+1 I hav ethis layout. I supose cache was invalidaed and here we are.

**Comment by wdamien** [comment]
@mweitzman and @alundiak  Can you post any console logs that you see?  This issue usually occurs when one (or more) of the support scripts fail to load, with more debugging information we can track down exactly whats happening here.  I also tested in Ubuntu 14.04, using Chrome, but cannot reproduce it on my end.

**Comment by alundiak** [comment]
My previous comment referred to my reproduced case on Chrome/Windows 7.

I can't reproduce bug on Mac OS via Chrome.
<img width="1435" alt="screenshot 2015-10-01 18 45 40" src="https://cloud.githubusercontent.com/assets/2131633/10227274/a7ccc1a4-686c-11e5-9f25-778c0b6fc7e1.png">

All urls goes to:
Origin:https://www.youtube.com

My AdsBlocker is DISABLED for this domain.

**Comment by mweitzman** [comment]
I just noticed that my ad-blocker is turned on, that's why I'm seeing this error.
My apologies.
It's wierd though, I also have the same ad-blocker running in Firefox and I'm not having any problems with the layout...

It's all on you now @alundiak , hope you can help to find a better solution for the REAL problem haha

Thanks to the developers!

**Comment by themowski** [comment]
I encountered this issue today for the first time (on two separate computers) and just tracked it back to the Ghostery add-on, which I recently installed on both machines. I'm running Firefox 40.0.3 and 41.0 on Windows 7 in both cases.

Ghostery picked up and blocked the Google AJAX Search API, specifically, the webfont.js script. I got around the issue by telling Ghostery to allow that script on regexr (see also the screencap below).

![regexr](https://cloud.githubusercontent.com/assets/13295249/10260219/39f71e0a-6938-11e5-9841-ecbb85c611d3.png)

I hope this helps! Regexr is super useful... it's a shame to think that people using Ghostery may miss out.

**Comment by mweitzman** [comment]
@themowski Your solution works PERFECT for me! I use ghostery myself and now I don't have to turn it off every time I use RegExr!
Thank you very much for your help!

**Comment by vince2010091** [comment]
Hello,
I have a similar problem but on Expression field, with a long regex, the scroll bar hide the regex
Regards,

UA: IE9 (no choice, corporate computer...)

**Comment by wdamien** [comment]
@vince2010091 can you log a different bug for your IE 9 issue, with some more details and, if possible, a screen capture that shows the issue? Thanks!

This also loosely relates to #57, we already want to switch away from using google apis since they cause issues for users in China.
