### ISSUE TITLE
command line mode for "Roll over a match or expression for details"

### ISSUE THREAD

**Issue by pdurbin** [gskinner/regexr#114]
I originally left this feedback at https://github.com/izahn/workshops/issues/2#issuecomment-145989409 but I'd be curious to know if there's a command line mode for "Roll over a match or expression for details."

I only ask because I'm pretty sure the "explain" feature at https://myregextester.com is powered by http://search.cpan.org/dist/YAPE-Regex-Explain/Explain.pm which can be called from the command line.

**Comment by wdamien** [comment]
RegExr doesn't offer any command line support, the entire site is written in client side javascript so its not really feasible for us to offer this. The only way I could possibly see supporting it would be to breakout the "explain" functionality into a node module, which is something we are not looking to build.
