### ISSUE TITLE
Run regex on multiple, separate strings

### ISSUE THREAD

**Issue by mnquintana** [gskinner/regexr#115]
Right now you can only supply one string as a test case (whatever you enter in the text box) - it would be really awesome to be able to run your regex against multiple test cases. This would be especially useful when testing any regex involving `^` or `$`, since you wouldn't be able to easily test for matches with only one test case.

Thanks for building such an awesome tool! :beers:

**Comment by Nightfirecat** [comment]
Seems like you can achieve the desired effect by just using the `m` (multiline) and `g` (global) flags: http://regexr.com/3c149

**Comment by gskinner** [comment]
Given the UI complexities this would introduce, can you provide any strong arguments for this feature beyond what the /m flag provides? Please feel free to reopen if so.
