### ISSUE TITLE
Hovering regex expression misbehaves when window smaller than minimum

### ISSUE THREAD

**Issue by acerspyro** [gskinner/regexr#117]
In Firefox at least, if you resize the window horizontally to something smaller than the minimal width, a scroll bar will appear at the bottom. Scrolling the page to the right and hovering the Regex expression results in input being moved to the left.

**Comment by lannymcnie** [comment]
Confirmed. Looks like the tooltip needs to be adjusted based on the horizontal scroll.

![Screenshot](http://screens.gskinner.com/lanny/Screen%20Shot%202015-11-05%20at%202.45.00%20PM.png)
