### ISSUE TITLE
Scroll bar hides Regex in expression bar

### ISSUE THREAD

**Issue by athomasmr23** [gskinner/regexr#118]
When the regex typed into the expression bar is long enough a scroll bar pops up that cover >50% of the typed regex expression making edits very difficult. I'm using IE 11.

**Comment by wdamien** [comment]
Thanks for the report! Confirmed that IE 11 and Edge require some style tweaks to make that scroll bar fit correctly.

Sample expression for testing:
http://regexr.com/3c7g0

![screen shot 2015-11-16 at 9 35 58 am](https://cloud.githubusercontent.com/assets/299050/11187911/9e880a02-8c45-11e5-8cb1-33d99a380600.png)
