### ISSUE TITLE
/\d*/g infinite

### ISSUE THREAD

**Issue by yoyo1218** [gskinner/regexr#123]
why /\d*/g infinite? It's right in javascript

**Comment by gskinner** [comment]
RegExr uses the JS RegExp engine.

`\d*` is infinite because it matches zero-length strings, so it can match nothing an infinite number of times.

**Comment by Nightfirecat** [comment]
For future reference, you can hover over the text "infinite" to see the following:

> **ERROR:** The expression can match 0 characters, and therefore matches infinitely.
