### ISSUE TITLE
Match tooltip results don't update until mouse move

### ISSUE THREAD

**Issue by wdamien** [gskinner/regexr#124]
Steps:
 Go to http://regexr.com/3bues
- Ensure the "Expression" text input has keyboard focus
- Hover your mouse over the blue match in the Text area until the match tooltip is visible
- Make a change using just your keyboard (don't move mouse) to the Expression that should update the match results

Notice the tooltip does not update until you move your mouse. I expected the results in the tool tip to update when I changed the expression. If my changes resulted in no blue highlighted text under my mouse, I would expect the tooltip to disappear.

**Comment by gskinner** [comment]
I'll look at this for v3.0

**Comment by gskinner** [comment]
Pushing to v3.1

**Comment by gskinner** [comment]
Fixed: 49799f411251c4e97d9f946bddab9ce81fbc44dd
