### ISSUE TITLE
Add a reset editor option

### ISSUE THREAD

**Issue by wdamien** [gskinner/regexr#129]
From @jaredbell

Minor usability issues, but felt that there was no clear way to reset the editor after it had been altered.

Suggestion would be explicit reset link somewhere (rough sample attached). Alternatively top logo could be used to reset by linking to home as, popup warns about saving vs. losing work, although this way isn't necessarily as clear.

![screen shot 2014-03-24 at 10 34 07 am](https://cloud.githubusercontent.com/assets/299050/12127588/54a8cc7c-b3b5-11e5-84d7-9c11984df388.png)

**Comment by gskinner** [comment]
what would be the use case for this? Any reason you wouldn't just use Undo?
