### ISSUE TITLE
Matched result/groups are trimmed in tooltip

### ISSUE THREAD

**Issue by ThaNarie** [gskinner/regexr#13]
Currently the matched result and groups in the match tooltip are truncated to fit in the tooltip.
So there is no way to see if your groups have the correct match (at the end) when working with longer texts.

Are there any plans to improve this? Like a sidebar/panel to show the whole content of a single match including all the matched groups (with a scrollbar for the whole panel or per group).
Where the info shown is based on the selected group in the main editor.

**Comment by Forecaster** [comment]
Could also perhaps highlight the group match in the text with a different color from the whole match.

**Comment by gskinner** [comment]
This has been addressed with the "Details" tool, and will be improved further in v3.0
