### ISSUE TITLE
Community items' star rating should be white when item is highlighted blue

### ISSUE THREAD

**Issue by wdamien** [gskinner/regexr#130]
From @trevordunn

What steps will reproduce the problem?
1. Select a community item (should highlight the list item to blue)
2. Hover over the star rating on the right of the item

What is the expected result?
Unless clicking the star rating does something different than loading the regular expression, it should be highlighted white whenever the item is highlighted blue (like this: http://grab.by/vpBC)

What happens instead?
The star rating stays black (like this: http://grab.by/vpBG)

**Comment by gskinner** [comment]
This is fixed in v3.0

**Comment by gskinner** [comment]
Fixed in 3
