### ISSUE TITLE
which flavour of regular expression?

### ISSUE THREAD

**Issue by Siddhant** [gskinner/regexr#131]
Hello, I think it is really important to mention on the front page of the website which flavour/dialect of regular expression is the tool for.

In the questions it says: "RegExr uses your browser's RegExp engine for matching." What does that mean for the user? Is it the Javascript flavour of regex? Whar version? etc. Kindly make this more clear, and highlight this specific information somewhere on the main page. This is the very first question which comes to mind (well, at least to my mind) when someone opens your website.

**Comment by Morketh** [comment]
> While the core feature set of regular expressions is fairly consistent, different implementations (ex. Perl vs Java) may have different features or behaviours.

> RegExr uses your browser's RegExp engine for matching, and its syntax highlighting and documentation reflect the JavaScript RegExp standard.

Information is under the Help -> RegEx engine option.

**Comment by mattalexx** [comment]
+1

**Comment by gskinner** [comment]
This will be more up-front in v3.0 with the Engine selection control.

**Comment by gskinner** [comment]
Addressed (hopefully) in v3, with the Engine / Flavor dropdown, help icon, and Help content.
