### ISSUE TITLE
Feature: convert Regexp to String(Language Specific) 

### ISSUE THREAD

**Issue by ahmedshuhel** [gskinner/regexr#139]
Take this regexp for example `\s*\*\*\s*` this detects `**`. To make it a javascript string we have to add all these language specific escape characters. So in javascript string  the above regexp become:
`'\\s*\\*\\*\\s*'`

It would be nice if the software offers a way does these conversion for different languages like javascript, C#, F#, Java, PHP etc and let us copy the string. 

I would like to contribute this feature.

Thank you for this wonderful tool. I love it and use exclusively.

**Comment by wdamien** [comment]
@ahmedshuhel we are planning support for other types of RegExp, which will include language specific copying. Feel free to add ideas or suggestions to #32
