### ISSUE TITLE
Add support for Group Names

### ISSUE THREAD

**Issue by ruisilva450** [gskinner/regexr#140]
Add support for this type of syntax:

Regex: **(?<PostalCode>\d{4}-\d{3})**
Example Text: The postal code is **4445-150** ...

The output should be something like:
Match 1:
PostalCode -> [19-27] -> `4445-150`

**Comment by gskinner** [comment]
I'm not totally sure what you're asking for here. Where is the text "PostalCode" coming from in your example?

If you're just asking for named groups like: `(?'name'foo)`, that is coming as part of #32. Feel free to reopen if you're talking about something else.
