### ISSUE TITLE
Small bug that allows you to get rid of the closing forward-slash and flags

### ISSUE THREAD

**Issue by FlatChest** [gskinner/regexr#141]
By using the Insert button you can override characters, allowing this to happen:
![oh shit](http://i.imgur.com/Fp3Vhca.gif)

**Comment by wdamien** [comment]
Thanks for the report! However, we are already tracking this issue here, #18 . If you have any ideas on how to fix this, we welcome PR's.

**Comment by FlatChest** [comment]
Guess I didn't look hard enough, sorry.
