### ISSUE TITLE
\x{...} Notation Support for Unicode Characters

### ISSUE THREAD

**Issue by dgreatwood** [gskinner/regexr#146]
Would it be possible to support \x as well as \u?

In the example I'm looking at right now, to match ASCII or "fancy" inverted comma -
    [\x{2019}'] 
does not match unicode inverted comma, whereas
    [\u2019'] 
works fine

The \x{...} seems fairly common, at least it was used in some regex samples I was reusing.

Thanks much.

**Comment by gskinner** [comment]
This falls under the umbrella of our old friend #32, which is implemented in v3.0
