### ISSUE TITLE
Says there's a match when there is no match

### ISSUE THREAD

**Issue by Xogle** [gskinner/regexr#151]
![screen shot 2016-05-12 at 13 19 09](https://cloud.githubusercontent.com/assets/6294118/15223795/26fda7ea-1844-11e6-8e20-2f04dc8a2fb0.png)

**Comment by gskinner** [comment]
It is matching your final pattern "$" (ie. end anchor), which is a position, not a character, so nothing is highlighted.

**Comment by Nightfirecat** [comment]
If you add the global flag, you'll find that rather than saying that there's only 1 match, it will say that the regex matches infinitely: http://regexr.com/3ddjs
