### ISSUE TITLE
Or Operator in Character Set Identifies as Character

### ISSUE THREAD

**Issue by Comandermuffif** [gskinner/regexr#156]
`/^([A-Z|0-9]+)$/gm`
The above when moused over the OR operator, '|', is identified as a character and not an operator although the expression still evaluates correctly.

![capture](https://cloud.githubusercontent.com/assets/3998757/17111836/5fa5d362-5271-11e6-9555-dc6213dde7ad.PNG)
![capture](https://cloud.githubusercontent.com/assets/3998757/17111962/de58a892-5271-11e6-9f4d-df46d329e53f.PNG)

**Comment by lannymcnie** [comment]
In the character set, '|' is a character, and not an operator. For example, if you include the pipe character in your first example's text, it will highlight.
![screen shot 2016-07-25 at 12 25 04 pm](https://cloud.githubusercontent.com/assets/590731/17112334/ddba3f36-5262-11e6-94c7-a128918a2ef3.png)

If you want to use a character set that has any number of letter OR number characters, you need two separate character sets:

```
/^([A-Z]+|[0-9]+)$/gm
```

The above regexp will allow any number of uppercase letters and numbers (but not mixed). Here is a sample: http://regexr.com/3dsg1
