### ISSUE TITLE
Wrong display for \A and \Z

### ISSUE THREAD

**Issue by JetStream96** [gskinner/regexr#157]
For example, \A shows as "escaped character (Matches a "A" character)" instead of start of string.

**Comment by Nightfirecat** [comment]
[The Javascript regex engine doesn't contain `\A` or `\Z`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#special-word-boundary). ([another source](http://stackoverflow.com/a/21786514))

Use `^` for start of string and `$` for end of string instead.

**Comment by JetStream96** [comment]
Ahh sorry I didn't know that. I thought it was a bug.
