### ISSUE TITLE
Security: Add HTTPS Support

### ISSUE THREAD

**Issue by Foorack** [gskinner/regexr#158]
Every unencrypted HTTP request reveals information about a user’s behavior, and the interception and tracking of unencrypted browsing has now become commonplace. Today, there is no such thing as non-sensitive web traffic, and public websites should not depend on the benevolence of network operators.

Password sniffing is easy and common thanks to the likes as Firesheep, NSA/GCHQ are spying on transatlantic cables, and global Internet in general. Unencrypted websites are subject for ads injection and as attack initiators.

An incredible written post regarding this topic: 
https://scotthelme.co.uk/still-think-you-dont-need-https/

CloudFlare describes the advantages of SSL like this:
- Security: ensure that no one is intercepting web traffic 
- Trust: by displaying a green lock image, the website increases visitors’ trust 
- Search ranking boost: Google ranks sites that have SSL higher in search results 
- (Regulatory compliance: financial institutions and web stores that work with credit cards must comply with regulations and adopt SSL on their websites)

If you are from the US I strongly recommend reading these articles: 
- http://arstechnica.com/tech-policy/2014/09/why-comcasts-javascript-ad-injections-threaten-security-net-neutrality/ 
- https://gigaom.com/2015/02/19/dont-let-att-mislead-you-about-its-29-privacy-fee/

Mozilla and the Chromium Project have also announced their intent to deprecate HTTP protocol in favor of HTTPS. The relative posts can be found here: 
https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/ 
https://www.chromium.org/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

Enabling HTTPS is not hard, there are no performance drawbacks (https://istlsfastyet.com/), certificates are free (https://letsencrypt.org/), and CloudFlare provide free SSL service.

**Comment by Nightfirecat** [comment]
It looks like the site has an SSL certificate (albeit for the wrong domain), but redirects HTTPS to HTTP.

I'm in favor of getting a certificate set up and directing all traffic to HTTPS.

**Comment by MekliCZ** [comment]
I would not use CloudFlare because they do MITM attack and supply their own certificate to user. The communication should be encrypted from user to regexr, even if there are no private information.

**Comment by Foorack** [comment]
I mostly recommended CloudFlare because it is simple to set-up and works with most hosting solutions. LetsEncrypt or another certificate authority should work just as well. It is not important way method is used, as long as the site is secured. 😃

**Comment by yiweig** [comment]
+1. Any movement on this effort?

**Comment by lannymcnie** [comment]
Updated to SSL today.

**Comment by woollsta** [comment]
@gskinner  Certificate looks to have expired today:

![image](https://user-images.githubusercontent.com/3171254/60955706-50f06900-a2f9-11e9-88f5-c3a729c3e4e2.png)
