### ISSUE TITLE
"Use" feature

### ISSUE THREAD

**Issue by Serabass** [gskinner/regexr#159]
Can you make a feature for building example code blocks for many langs (See the RegexBuddy app)? For example, if I have a regexp I want to use it for Java or C#, RegexBuddy has a lot of code templates for them but database is offline (as RegexBuddy). I would like to see this feature in your pretty tool.
I could create some repository where people can make a bundle of templates.

**Comment by gskinner** [comment]
Good idea. I don't think it's going to make it into v3.0, but I'll consider it for v3.1

**Comment by gskinner** [comment]
Tracking this under #198
