### ISSUE TITLE
Unicode flag "u" is working, but not listed in RegExr

### ISSUE THREAD

**Issue by ezaca** [gskinner/regexr#161]
I found the issue #15, when a user asked for the Unicode flag.

Back then (Apr 2014), Javascript did not supported the flag. Now, Mozilla MDN claims Firefox already do support Unicode. I believe their documentation is outdated, as I am using the "u" flag in Opera (V8 Engine) right now.

It is possible to add the flag now?

(Just to let you know, your site is amazingly useful!)

**Comment by gskinner** [comment]
Yes. This is planned in the next version, with feature detection.

**Comment by pmkary** [comment]
@gskinner can you explain what is it that you're planning to add as _feature detection_?

**Comment by gskinner** [comment]
This is working in v3.0 (not pushed or public yet). I may add a warning or something to it though.

Feature detection is very simple, since the RegExp constructor will throw an error for anything it doesn't recognize.

```
function testFlag(flag) { try { new RegExp(".",flag); } catch (e) { return n; } }
```

**Comment by ezaca** [comment]
Nice! The only browser I have tested that does not support "u" flag was Internet Explorer 10. Even Edge supports it :)

Will the Sticky (y) flag be included too? Not thaaat useful given its function, but seems more consistent to add it along with Unicode (u) flag.

**Comment by gskinner** [comment]
In v3.0

**Comment by gcjuan** [comment]
Hi @gskinner !

I tried to test the regex pattern that I found [on this cool tutorial](https://andrewwoods.net/blog/2018/name-validation-regex/) for matching people's names (including Unicode characters like ñ,á,é,ó,ç,etc) but couldn't do it in RegExr cause I cannot put the /u flag for PCRE checks.

Is it still in RegExr's roadmap? just a reminder :smile:

**Comment by ezaca** [comment]
Hello, @gcjuan . I confirm the feature was already added to the site. In the flags, you can select the "Unicode" flag or just paste your expression with the .../u flag.

For your specific code, at least in Chrome (v. 75), with the unicode flag the browser was very angry about the `\x{????}` pattern. I found it expected something like `\u????`. It also refused to understand the invalid escapes `\ `, `\'` and `\-`. For that, remove the \ character and place the hyphen (-) as the very first or very last character in the range.

Here is a working version of the pattern:
`/^[A-Za-z\u00C0-\u00FF][A-Za-z\u00C0-\u00FF'-]+([ A-Za-z\u00C0-\u00FF][A-Za-z\u00C0-\u00FF'-]+)*/u`

Notice the error on `\x` occurs only when the unicode flag is present, like it would in browser Console.

Because you have this code from a tutorial, the error may be caused due to incompatibility or different versions of the regular expression specs.

**Comment by gcjuan** [comment]
Hello, @ezaca . First of all thanks for your little research and for your answer.

I've found RegExr shows the \u flag only if JavaScript regex syntax is selected.

What you mention is only valid for JavaScript Regex specs and what I'm trying to match is a string on PHP (PCRE's "game rules"). As you can see on [this linked post](https://www.regular-expressions.info/unicode.html), JavaScript doesn't support Unicode by itself but can deal with \uFFFF syntax. On the other hand, PCRE does not support \uFFFF, it uses \x{FFFF} instead. I recommend you to test these behaviors at [www.regex101.com](https://www.regex101.com).

Furthermore, I cannot confirm that escaping characters like \' is being refused by RegExr neither for Javascript nor for of PCRE. It's simply working for me on both Firefox and Chrome =(
