### ISSUE TITLE
Replace with group doesn't work

### ISSUE THREAD

**Issue by qwertyphile** [gskinner/regexr#165]
**Find:**
(.+,.+,(left|right),.+,.+\n).+,.+,\2,.+,.+\n

**Replace:**
\1

**Text Example :**
0,22,right,0,0
23,0,left,1,0
0,22,right,0,0
23,0,left,1,0
0,22,right,0,0
0,0,left,-22,0
0,0,right,0,-22
0,22,right,0,0
23,0,left,1,0
0,22,right,0,0
23,0,left,1,0
0,22,right,0,0
23,0,left,1,0
0,22,right,0,0
23,0,left,1,0
0,22,right,0,0
23,0,left,1,0
0,22,right,0,0
23,0,left,1,0
23,0,left,1,0

**Purpose:**
Find lines out of alternating order and replace with the first line only. This implementation works in Notepad++ but not RegExr.

**Browser:**
Vivaldi 1.4.589.38 (Stable channel) (32-bit)
Revision: afa9b018e32575fcd8f8283755a315804ecf0671
OS: Windows 
JavaScript	 V8 5.3.332.47

**Comment by lannymcnie** [comment]
Saved pattern: http://regexr.com/3ee4m

Seems to work. I added a ? at the end to capture the last instance which had no line break after it.

**Comment by qwertyphile** [comment]
Thanks,

The "Cheat Sheet" was a bit misleading. Trusting it as my only reference I thought '\1' would reference the fist group. This worked in Notepad++. Now looking at your saved pattern I see that '$1' is the proper way.

Cheers
