### ISSUE TITLE
Unescaped / within a negated set doesn't throw an error

### ISSUE THREAD

**Issue by benchew** [gskinner/regexr#168]
I was trying the expression ([^/]*)\/([^/]*)\/([^/]*) and I wasn't getting an error due to the unescaped forward slashes.

**Comment by gskinner** [comment]
I just tested this expression, and it's working correctly for me. The two slashes outside of sets are displaying errors, and the slashes in the set are not, as expected.

If you're seeing something else, could you please reopen & provide more info (browser / OS version)?

**Comment by benchew** [comment]
Hmm, maybe I am missing something, but until I escaped the slashes in the set, my regex didn't work correctly in perl.

**Comment by gskinner** [comment]
RegExr uses the JS regular expression engine, which is generally a safe subset for all other RegEx flavors. Looks like you found a rare example of a supported feature that behaves a bit differently between engines. We'll keep this in mind as we work on supporting other flavors fully.

**Comment by Nightfirecat** [comment]
Regexr specifically uses your browser's regex engine (JavaScript), so there are likely some differences between it and Perl regex.

**Comment by benchew** [comment]
Ah, got it. Thanks for getting back to me. I love what you guys have done with regexr.
