### ISSUE TITLE
Newlines and returns not highlighted? 

### ISSUE THREAD

**Issue by jaepage** [gskinner/regexr#169]
At: http://www.regexr.com/

…if I set the expression to be: `/\s/igm`

…and I type: 

```
return
soft return
enter
```

…I see only highlighted the space character between `t` and `r` on the second line. 

Why don't I see any newlines/returns hightlighted?

**Comment by Nightfirecat** [comment]
Here's a copy of your test case: http://www.regexr.com/3erm3

I agree that there's a bug, however it's capturing the right number of matches, as it displays "3 matches". The bug seems to be that the newlines are not highlighted in any way.

**Comment by jaepage** [comment]
Technically not the exact text. I see now when I type return, soft return, and enter characters, it reports four matches in the upper right (the four being the space character). 

But yes, the exact bug would then be lack of highlighting. Thank you for clarifying.

**Comment by gskinner** [comment]
This is a tough one. CodeMirror (the editor library we use) doesn't preserve newlines. In v3.0, we will be showing invisible characters, but unfortunately probably won't be highlighting newline characters. I want to work out a solution, but it's likely after v3.0.

**Comment by gskinner** [comment]
Tracking this as #206.
