### ISSUE TITLE
Add ability to collapse the library

### ISSUE THREAD

**Issue by gskinner** [gskinner/regexr#17]
It would be nice to be able to collapse the Library panel when it isn't needed.

Concept for collapsed view:
![librarymin](https://cloud.githubusercontent.com/assets/157128/2607178/cd09bf60-bb59-11e3-9b86-ddf9db9ef552.jpg)

Visual update for expanded view, showing new icon & slightly adjusted row item icons:
![librarymax](https://cloud.githubusercontent.com/assets/157128/2607190/ee7e2f32-bb59-11e3-9b83-1d62b453ef35.jpg)

**Comment by mklemarczyk** [comment]
:+1:

**Comment by gskinner** [comment]
Finally coming in v3.0. Hooray for Flexbox!

**Comment by gskinner** [comment]
This is implemented in v3.0.
