### ISSUE TITLE
Letter counter in the text field

### ISSUE THREAD

**Issue by Aslanex** [gskinner/regexr#171]
Hi, how about adding a tool to get the letter count of selected text? That would be very handy when writing a regex based on numbers.

**Comment by gskinner** [comment]
That's not a bad idea. Could potentially just put it in fairly subtle grey text in the Text header, left aligned. "sel range: 3-12" or similar.

**Comment by gskinner** [comment]
Most editors show this as line / column, would that be what you'd like to see?
`ln 20, col 72`

**Comment by jeff-hykin** [comment]
<img width="193" alt="screen shot 2017-12-07 at 9 16 47 am" src="https://user-images.githubusercontent.com/17692058/33722384-65f96722-db2f-11e7-9dde-0fa76adf3d35.png">
I think he is looking for the `(6 selected)` part of that

**Comment by gskinner** [comment]
Ok. I've added this information to a tooltip that appears when mousing over the results bubble in the Text header. This makes it available in the odd case that you need it, without cluttering the interface with info that I don't think is useful to 99% of users.

![screen shot 2017-12-07 at 11 13 43 am](https://user-images.githubusercontent.com/157128/33731245-ba25879e-db3f-11e7-9c9f-25b5f4f9e0aa.png)

**Comment by gskinner** [comment]
This update is now live.
