### ISSUE TITLE
Regex provided doesn't match all lines, but works ok in Java (and Clojure) code

### ISSUE THREAD

**Issue by SteveInNZ** [gskinner/regexr#173]
Here's the regex I used:

`([A-Z]*)(\(.+?\))*([A-Z]*)`

Here is the sample input:

```
ADVENT
A(1x5)BC
(3x3)XYZ
```

What happens is that the regex should match *all* lines, but in RegExr
it only matches the 1st line - the 2nd and 3rd lines are not matched.
I can confirm this, because the regex I used works fine, and matches all
lines with the same sample input in Java, and Clojure.

It also works fine in:
https://regex101.com/
http://regexstorm.net/tester
http://rubular.com/

etc

**Comment by Nightfirecat** [comment]
Putting in such an input shows the following error message:

> **ERROR:** The expression can match 0 characters, and therefore matches infinitely.

http://regexr.com/3etmv

**Comment by gskinner** [comment]
Correct. Your pattern can happily match a zero-length string, and as such is dangerous to use in many languages due to infinite matching. We could work around this, but I think it's better to surface it so users can write a "safe" pattern. Open to feedback.

**Comment by SteveInNZ** [comment]
Ok, I think I understand now. However, there are two issues here:

1) The regex is dangerous, is an error in RegExr, and should not be used. So, I have rewritten it into something that does a much better job.

2) The regex works fine in Java (and Clojure) and doesn't report an error in all those sites I mentioned above.

As such, I'm happy to leave this issue closed. Thanks for taking the time to consider this, and to help me out.
