### ISSUE TITLE
URL test rexex'es (from https://mathiasbynens.be/demo/url-regex)

### ISSUE THREAD

**Issue by Rava77** [gskinner/regexr#174]
I try to check the URL test rexex'es (from https://mathiasbynens.be/demo/url-regex) and I am interested in the one that has the most hits in "should match" and best none in "should not match" from the given URL list. And would choose the shortest regex I deem sufficient enough...

I started with the shortest ones, but all the below listed fail with the same error:
"unescaped forward slash"

When I escape that via adding "\\" in front of each underlined "/" regexr seems to accept the regex as valid, but the regex gives no results.

The ones I tried and that failed are these:

```
@stephenhay (38 chars)
@^(https?|ftp)://[^\s/$.?#].[^\s]*$@iS

@imme_emosol (54 chars)
@(https?|ftp)://(-\.)?([^\s/?\.#-]+\.?)+(/[^\s]*)?$@iS

@gruber (71 chars)
#\b(([\w-]+://?|www[.])[^\s()<>]+(?:\([\w\d]+\)|([^[:punct:]\s]|/)))#iS

@krijnhoetmer (115 chars)
_(^|[\s.:;?\-\]<\(])(https?://[-\w;/?:@&=+$\|\_.!~*\|'()\[\]%#,☺]+[\w/#](\(\))?)(?=$|[\s',\|\(\).:;?\-\[\]>\)])_i

```

Sadly, I myself are not very good with regex... also I deem regex a very powerful tool.

Cheers

**Comment by gingerbeardman** [comment]
These use custom delimiters, see https://github.com/gskinner/regexr/issues/185 

Custom delimiters are often used if the delimiter character is used in the regex itself, by changing the delimiter you don't have to escape that character in the regex and things become easier to read.

So you need to change them to remove the custom delimiter. 

regexr displays it's own delimiter //g

The first one would become:
`^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$`

which on the site it looks like this

`/^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$/g`

@Rava77 HTH

**Comment by gskinner** [comment]
Closing this, in favor of #185
