### ISSUE TITLE
Plus (+) quantifier is acting lazy, not greedy.

### ISSUE THREAD

**Issue by kamoroso94** [gskinner/regexr#175]
Given the regular expression `/[0#]*\.?[0#]+|[0#]+\.?[0#]*/g`, and the input

>0
>0.0
>0.
>.0

the tool matches each line (4 matches) except the third line, which only matches the first character (`0`).  It should match the entire line (`0.`).

**Comment by Nightfirecat** [comment]
I think your regex is behaving correctly... `/[0#]*\.?[0#]+|[0#]+\.?[0#]*/` behaves identically to `/([0#]*\.?[0#]+|[0#]+\.?[0#]*)/` meaning that your first capture group:

> 0
> 0.0
> 0

is captured by either option of the alternation, `/[0#]*\.?[0#]+/` or `/[0#]+\.?[0#]*/`

Once that is captured, neither of these options allow capturing of the next two characters:

> .
> .

so the first period is skipped, leaving us with the resulting second captured group of:

> .0
