### ISSUE TITLE
Start with \( doesn't get match

### ISSUE THREAD

**Issue by LucasMontero** [gskinner/regexr#176]
Given the regex \b(9|6|\\()[0-9-\)]{8,14}\b on text:

982-22-22-22
982222222
(982)-22-22-22
982-222-222

(982)-22-22-22 doesn't get match

**Comment by Nightfirecat** [comment]
[Your regex](http://regexr.com/3f2g5) doesn't match a starting paren because [`\b` would only match before the first word-character](http://www.regular-expressions.info/wordboundaries.html).

[Something like `/(\b[69]|^\()[0-9-)]{8,14}\b/m`](http://regexr.com/3f2g8) would get around this issue.

**Comment by LucasMontero** [comment]
Thank you for your answer 👍
