### ISSUE TITLE
Would be useful to be able to deep link Expression and Text via url - either hash or query string?

### ISSUE THREAD

**Issue by Arrow7000** [gskinner/regexr#178]
The Regulex site automatically updates the hash with the regex - like this https://jex.im/regulex/#!embed=false&flags=&re=%5E(a%7Cb)*%3F%24.

It would be useful if Regexr could also update the url as the user types. 

Or if this would make the url look too messy, it would at least be useful to have a share/link button that would generate a url with expression and text data. When clicked on this would automatically populate the fields accordingly. 

This would mean instead of people just using this for themselves, they could show others how a particular regex matches or doesn't match a particular set of strings.

**Comment by Arrow7000** [comment]
Having posted this, let me say that I'd be happy to implement and create a pull request for this myself :smiley: 

I'll only start though if one of the project maintainers say that they'd approve this, so I'd appreciate your feedback!

**Comment by Arrow7000** [comment]
The way I visualise this would be by having the url be something like 

`http://regexr.com?regex=%5E%5C%2Fpage(%5C%2F%7C%5C%2Findex(%5C%2F)%3F)%3F%24&flags=gm&text=%2Fpage%0A%2Fpage%2F%0A%2Fpage%2Findex%0A%2Fpage%2Findex%2F%0A%2Fpage%2Findex.json%0A%2Fpage%2Findex.json%2F`

**Comment by lannymcnie** [comment]
There is a fairly robust save & share. You can save patterns, which generates a URL (and changes the browser URL).

![screen shot 2017-01-26 at 4 48 42 pm](https://cloud.githubusercontent.com/assets/590731/22355349/5a1f145a-e3e7-11e6-8fee-ef04daaf1dab.png)
![screen shot 2017-01-26 at 4 48 49 pm](https://cloud.githubusercontent.com/assets/590731/22355350/5a3819d2-e3e7-11e6-8ff3-fc434e49ed44.png)

![screen shot 2017-01-26 at 4 47 13 pm](https://cloud.githubusercontent.com/assets/590731/22355300/311a0498-e3e7-11e6-8001-e96d1c2a4e97.png)

**Comment by Arrow7000** [comment]
@lannymcnie ah I didn't know about that. 

Maybe exactly for that reason it could be worth updating the url as the user types, so that it is crystal clear that the link is shareable and will automatically populate the page with exactly what the user is currently seeing?

**Comment by Arrow7000** [comment]
Also it looks like saving requires you to add a name with a few more optional fields - which immediately would put someone like me off using it.

**Comment by lannymcnie** [comment]
You have to add the name and other fields when you add it to the community (since it shows up in search). If you don't select that option, it just saves it privately and you can share it as you see fit.

Cheers.
