### ISSUE TITLE
www version of Website should redirect to non-www

### ISSUE THREAD

**Issue by impressivewebs** [gskinner/regexr#179]
Go to:

http://www.regexr.com/

URL stays as is. But the same thing happens if I go to:

http://regexr.com/

Not a really big deal but it's generally good practice to pick one.

**Comment by Sopor-** [comment]
http://www.regexr.com is not even working anymore :(
I was opening your site my bookmarks and first i believed the site was down but it wasn't, so you should really fix that redirect thing.

**Comment by gskinner** [comment]
@Sopor- can you provide more info? It's working for me here. Thanks.

**Comment by Sopor-** [comment]
@gskinner 
I only get this in my web browser:
```
Server not found

Firefox can’t find the server at www.regexr.com.
```
If i try to ping it, it won't even be there
```
C:\>ping www.regexr.com
Ping request could not find host www.regexr.com. Please check the name and try again.

C:\>ping regexr.com

Pinging regexr.com [72.47.228.225] with 32 bytes of data:
Reply from 72.47.228.225: bytes=32 time=178ms TTL=46
Reply from 72.47.228.225: bytes=32 time=177ms TTL=46
Reply from 72.47.228.225: bytes=32 time=177ms TTL=46
Reply from 72.47.228.225: bytes=32 time=177ms TTL=46

Ping statistics for 72.47.228.225:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 177ms, Maximum = 178ms, Average = 177ms
```

**Comment by impressivewebs** [comment]
Works for me at the moment. But I still think it's best practice to pick either WWW or non-WWW, as the original issue pointed out.

**Comment by Sopor-** [comment]
`www` should be the default site imo. It is still a homepage and therefore the url should start with `www`. Sorry that i don't agree to your suggestion @impressivewebs but i do agree to that one of the addresses should redirect to the other.

**Comment by impressivewebs** [comment]
Oh yeah, no problem. The point was more about picking one, but I personally like without the WWW for certain types of URLs.

**Comment by wdamien** [comment]
Fixed.  www.regexr.com/ now redirects to regexr.com/.  Thanks for suggestion @impressivewebs!

**Comment by Sopor-** [comment]
Now it works for me too. I get redirected from `http://www.regexr.com` to `http://regexr.com` :)
