### ISSUE TITLE
"Inactive" slash and flags in expression bar can be overwritten

### ISSUE THREAD

**Issue by mepsoid** [gskinner/regexr#18]
Put cursor to the end of the string, change keyboard insert mode and you will be able to type some chars that will overwrite finishing slash and flags.

**Comment by FlatChest** [comment]
I don't have much experience with JavaScript, but it might be an idea to change this ![](http://i.imgur.com/BG2xFcn.png) into a separate, uneditable text field that is always placed behind the regex text field?

**Comment by gskinner** [comment]
I finally spent a bunch of time with this. It definitely looks like a CodeMirror bug with their overwrite mode, in that it doesn't respect the atomic/inclusiveRight settings on the text range.

Given that, it doesn't seem likely to fix this issue while preserving overwrite, so I have disabled overwrite mode for the Expression field via a0db58d
