### ISSUE TITLE
RegExp match Chinese issue

### ISSUE THREAD

**Issue by maicss** [gskinner/regexr#182]
`/[\u4e00-\u9fa5]/` should match `（）` .

In Javascript runtime, this expression match fine, but [regexr](http://www.regexr.com/) cannot match.

**Comment by Nightfirecat** [comment]
It doesn't look like your regex matches that string...

```
> "（）".match(/[\u4e00-\u9fa5]/)
null
```

`u9fa5` is code point 40869, and the two characters provided are code points 65288 and 65289:

```
> "（）".codePointAt(0)
65288
> "（）".codePointAt(1)
65289
```

**Comment by maicss** [comment]
sorry, my fault..., I mixed some other char, so I got a true.

Thanks.
