### ISSUE TITLE
Support for (?#Comments)

### ISSUE THREAD

**Issue by Soumyanon** [gskinner/regexr#188]
Hi, 

I use regexr to check longer PHP-style regex strings. To keep the regex more readable I use comments on strategic places. However, if I need to check why a certain regex is not working I have to strip all comments from the string, because regexr does not support the comments. 

It would be nice if regexr would just ignore those comments. And it would be even better if it shows the comments in the explanation as well. 

Thanks in advance and keep up the good work!

**Comment by Nightfirecat** [comment]
The regex flavor employed by Regexr is Javascript Regex which, far as I can tell, does not support comments. I'm going to throw this in the pile of issues that would be solved by #32.

**Comment by gskinner** [comment]
Right. #32
