### ISSUE TITLE
Parse Branch Reset Groups

### ISSUE THREAD

**Issue by huanghe2015** [gskinner/regexr#194]
If the praser of regex was written by yourself,it's quite important to add support of new feature that is written in this page:https://www.hackerrank.com/challenges/branch-reset-groups

**Comment by gskinner** [comment]
This should be supported via the PCRE flavor in v3.0

**Comment by gskinner** [comment]
Parser now recognizes this syntax, but doesn't properly number the groups yet. Significant re-architecture to support. For now, it flags it with an error that describes the behaviour.

**Comment by huanghe2015** [comment]
Thanks for attention.

**Comment by gskinner** [comment]
I've improved support for this in the lexer, and it will be included in the next update. It removes the error, and correctly numbers groups in the branch reset group. It will still only highlight the first "group X" when rolling over a reference, but supporting that will require a more in-depth refactoring.
