### ISSUE TITLE
Reference error at escaped control character

### ISSUE THREAD

**Issue by RunDevelopment** [gskinner/regexr#195]
In the reference section at escaped control character, there is a mistake:

> This can range from \cA (NULL, char code 0) to \cZ (EM, char code 25).

This is incorrect as `\cA` matches char code 1 and `\cZ` char code 26. The example, however, is correct, as `I` is the ninth character.

**Comment by gskinner** [comment]
This has been updated in the v3.0 reference content (not pushed yet).

**Comment by gskinner** [comment]
Fixed in v3
