### ISSUE TITLE
Entire "share" feature COPY to clipboard is broken in Chrome

### ISSUE THREAD

**Issue by CollinChaffin** [gskinner/regexr#196]
FYI, not sure how ANYONE using Chrome is using the "share" COPY feature, since it's 100% broken due to the fields being set READONLY.

To reproduce:  Simply click the clipboard icon (which incorrectly does the animation and incorrectly indicates the copy has taken place).  Check clipboard and go down the list of URL, Expression, Pattern, Javascript.  NONE actually copy to clipboard.

To fix:  Open F12 devtools, navigate to:

![snag_8-15-2017_07-18-01](https://user-images.githubusercontent.com/9301483/29315668-02990b5a-818a-11e7-90fa-d8bdeae51c77.png)

And delete the "readonly" tag.  Without refreshing the page, repeat the above for all four and only then does clicking the "clipboard" icon to the right of each, word as intended.

**Comment by wdamien** [comment]
Sorry to hear your having issues. This is actually the first time I've heard of copy not working.  I just tested this on Chrome 60, Windows 10, and the copy feature works without any issue.  Can you provide any more details on how to reproduce this? (Chrome version, OS version, and any relevant console output).  Thanks!

**Comment by CollinChaffin** [comment]
hmm Just tested on three different systems all Win7x64 with the latest Chrome x64 DEV build (Version 62.0.3178.0 (Official Build) dev (64-bit)).  Was sure to disable ALL Chrome extensions and even tried it in incognito mode - how can it work for you since your code sets all those fields readonly as in my screencap above?  Also, then why when I delete that readonly attribute on the live site and flip right back now because the 4 fields can actually be clicked for content (because they are now not read only) is the copy to clip code working?  The copy code is fine, in fact everything is fine but to my knowledge, you cannot ask Chrome to select text to then clip to clipboard on a protected, UNSELECTABLE text box with that readonly flag set so more importantly I have a full lab set up can you tell me what OS and browser build you are using that IS working?

Mind you, are you actually testing with a blank clipboard to verify it is actually populating the data?  I ask because yes, when I click the clip buttons I get the cute animation that states "Copied!".....but again it's not able to get to the data.  I will also work on setting up a full javascript breakpoint debug and just screencap the whole thing for you to show you that the actual clip copy code is not able to act on those read-only text boxes and also show you live how removing that flag then allows your clip code to work (and hopefully clarify for you why as well).  Love the site so happy to do anything I can to make it better for everyone!

**Comment by gskinner** [comment]
ReadOnly should not prevent selection. It doesn't in any other browser. It looks like a bug in Chrome Canary - the feature works in Chrome v60, but I can confirm that it (and selection of ReadOnly text fields in general) is broken in v62.

You might want to report this issue to the Chrome team, since it appears to be an injection. If you do, I'd appreciate if you can provide the report link here.

Thanks for all the information, and for taking the time to report this!

**Comment by gskinner** [comment]
I submitted this issue via Canary's "Report an issue..." dialog.
