### ISSUE TITLE
Support Named Capturing Groups

### ISSUE THREAD

**Issue by michael-hawker** [gskinner/regexr#197]
http://www.regular-expressions.info/named.html

Saw some other group related issues, but didn't see named groups called out specifically.

**Comment by Nightfirecat** [comment]
[JavaScript does not support named capture groups](https://stackoverflow.com/questions/24859190/javascript-named-capture-groups).

**Comment by lannymcnie** [comment]
This will be addressed with the multiple language updates, which are in progress.
