### ISSUE TITLE
Implementation of upper and lower case transformations

### ISSUE THREAD

**Issue by AntonioRedondo** [gskinner/regexr#200]
Would it be possible to implement some operator which would allow to transform upper case to lower case matched text and vice versa?

For example, having:

```
THIS IS AN EXAMPLE TEXT
```

would transform somehow to 

```
this is an example text
```

Some text editors implement this feature with `\U`, `\L` and `\E` operators. The below regex:

```
\([^ ]*\) \(.*\)
```

and the below substitution pattern

```
\L\1\E \2
```

will transform the top text to

```
this IS AN EXAMPLE TEXT
```

You can find more info about this on https://stackoverflow.com/questions/1159343/convert-a-char-to-upper-case-using-regular-expressions-editpad-pro

**Comment by gskinner** [comment]
This is not supported in JavaScript or PCRE. Looks like it isn't available in XRegExp either, which is likely our next target flavor. Closing for now, but happy to revisit if support becomes available.
