### ISSUE TITLE
Open website in a new tab on logo click

### ISSUE THREAD

**Issue by semanser** [gskinner/regexr#201]
I have an idea for a small improvement. I think that it will be a nice idea to make a website logo as a link that opens in a new tab. I use RegExr in many cases and sometimes it's very helpful to quickly open a new tab with RegExr. 
@gskinner what do you think? if it's ok, I will do this small PR.

**Comment by gskinner** [comment]
So, we now have a new button. Currently it just resets the current tab, but there is an opportunity to just have it open a new tab. Thoughts?

**Comment by semanser** [comment]
What if a `New` button will open a new tab. And also add a new button called `Clear`, just to clear current tab?

**Comment by gskinner** [comment]
I think we could set this up so that it works through the browser. So if you click new, it resets the current tab. If you hold cmd / ctrl and click new, it opens a new tab. I've already done something similar for loading community patterns.

**Comment by gskinner** [comment]
In the v3.2 release (just pushed), you can hold cmd / ctrl and click New (or load a pattern) and it will open in a new tab per your browser settings. Thanks for the feature request!

**Comment by semanser** [comment]
Great! 
@gskinner Thank you for your effort to make an amazing RegExr even better!
