### ISSUE TITLE
Capturing group does not work correctly

### ISSUE THREAD

**Issue by Hongbo-Miao** [gskinner/regexr#202]
It should return `hello`
http://jsbin.com/xuqoliq/edit?js,console
```js
var result = /here=(.*)/.exec('hihere=hello');
console.log(result[1]);      // hello
```

However, in regexr, it highlights `here=hello`
http://regexr.com/3h8s1

**Comment by lannymcnie** [comment]
This works as expected.

Highlighting shows the whole pattern, not just the one capture group. If you roll over the highlighted text, you can see the groups that are captured. Your sample shows group #1 is "hello".
