### ISSUE TITLE
Regex is required for dd-mmm-yy format

### ISSUE THREAD

**Issue by KushalMaz** [gskinner/regexr#203]
In an input box, I need to check user provides date in dd-mmm-yy format only (Ex: 27-Nov-17).
Below code snippet is not working properly. It would be helpful if anyone can suggest any alternatives or suggest any regex.

function Validate_Date() {
var ExpirationDate = Xrm.Page.getAttribute("FieldName").getValue();
var regEx = /^([012]?\d|3[01])-([Jj][Aa][Nn]|[Ff][Ee][bB]|[Mm][Aa][Rr]|[Aa][Pp][Rr]|[Mm][Aa][Yy]|[Jj][Uu][Nn]|[Jj][u]l|[aA][Uu][gG]|[Ss][eE][pP]|[oO][Cc]|[Nn][oO][Vv]|[Dd][Ee][Cc])-(19|20)\d\d$/;
alert(regEx.test(ExpirationDate));
}

Thanks

**Comment by Nightfirecat** [comment]
[Your regex seems to be working as advertised](https://regexr.com/3h91u).

Please note, this is an issue tracker for the software which runs the site regexr.com, not a help board for troubleshooting regular expressions... Are you experiencing any issues with the site itself?

**Comment by lannymcnie** [comment]
Agreed, this seems to work. The pattern @Nightfirecat posted seems to be the default. Here is a modified version: https://regexr.com/3h921

I am not sure why you used the character sets in your pattern -- I just made it case-insensitive.

**Comment by Nightfirecat** [comment]
@lannymcnie I had actually entered `31-Jan-2000` as text, but it doesn't seem to be loading when linking to the saved page. (likewise, yours also seems to be loading only default text) Bug?

**Comment by jeff-hykin** [comment]
I'm not sure what exactly the regex is being used for but heres a robust date checker function that even includes leap years and stuff. It returns true if the date is valid, false if invalid. Allows for day to be 1 digit when appropriate.
```
function IsStringAValidDate(string_) 
    {
        date_matcher_31days = /^(31|30|[0-2]?[0-9])-(jan|mar|may|jul|aug|oct|dec)-(\d\d)$/i
        date_matcher_30days = /^(30|[0-2]?[0-9])-(apr|jun|sep|nov)-(\d\d)$/i
        date_matcher_feb    = /^([0-2]?[0-9])-(feb)-(\d\d)$/i
        if (string_.search(date_matcher_31days) > -1) { return true }
        if (string_.search(date_matcher_30days) > -1) { return true }
        if (string_.search(date_matcher_feb)    > -1) 
            { 
                feb_date_parsed = date_matcher_feb.exec(string_)
                day_ = feb_date_parsed[1]
                if (day_ == 29)
                    {
                        year_ = parseInt(feb_date_parsed[3])
                        year_ = year_ + 2000 
                        // leap years 
                        is_a_leap_year = null
                        if ((year_ % 4) != 0 )       { is_a_leap_year = false }
                        else if ((year_ % 100) != 0) { is_a_leap_year = true  }
                        else if ((year_ % 400) != 0) { is_a_leap_year = false }
                        else                        { is_a_leap_year = true  }
                        
                        if (is_a_leap_year) {return true}
                        else                {return false}
                    }
                return true
            }
        return false
    }
```
