### ISSUE TITLE
Heart a pattern not always work

### ISSUE THREAD

**Issue by HawkonDK** [gskinner/regexr#217]
If you wanna "heart" a pattern you need to reload the browser each time you do it, really ignoring

**Comment by gskinner** [comment]
Can you provide more info? I just double checked using these steps:
Go to Community, select a pattern, click heart, select a different pattern, click heart.
Go to My Patterns: both patterns are shown.
Go to Community: both patterns show as favorited.

Is it possible this is related to #127 ?

**Comment by gskinner** [comment]
Please feel free to reopen with more info.
