### ISSUE TITLE
Roboto Condensed

### ISSUE THREAD

**Issue by departure** [gskinner/regexr#218]
Please consider using a typeface easier to read. Regexr is an outstanding tool, **Roboto Condensed** is not doing it a favor, quite the opposite. 

Suggestion:
The **Inter UI** font family
https://rsms.me/inter

**Comment by gskinner** [comment]
Interesting, hadn't heard of Inter UI before. Looks like it's a drop-in replacement for Roboto that tweaks glyphs for better readability on screen. My main concern is that we're using Roboto Condensed, so switching to an uncondensed variant could cause some UI problems. I'll try swapping fonts though and see what the results are.

**Comment by gskinner** [comment]
I tried tossing it in. It's a nice crisp font, but I'm not super enamored with it, and it would definitely take some UI tweaks to accommodate.

Also, by default it's about 10x larger than Roboto Condensed, and would add about 250kb to RegExr's size. May be possible to trim down the glyph set to get it closer.

Appreciate the suggestion, but I think I'm going to leave it as is for now.
