### ISSUE TITLE
Lookaround inserts garbled characters in PCRE engine

### ISSUE THREAD

**Issue by HankAviator** [gskinner/regexr#227]
* Go to Menu - Reference - Lookaround
* Change RegEx engine to `PCRE`
* Double click `negative lookbehind`
* `(?&lt;!ABC)` is inserted into the expression

**Comment by gskinner** [comment]
Good catch. I've fixed this locally and it will be in the next version.

**Comment by gskinner** [comment]
Fix deployed.
