### ISSUE TITLE
regex [^\s] does not work?

### ISSUE THREAD

**Issue by koocies** [gskinner/regexr#228]
I've used this the ^ before to exclude characters I'm looking for. Using the default text on the page the regex "[^\s]+ v3" does not work. Tested this in other online regex testing tools and it works.

**Comment by Nightfirecat** [comment]
I'm seeing really intermittent behavior with the regex `/[^\s]+ v3/g`. If I type it manually, every character matching `[^\s]` is highlighted. If I type in `RegEx[^\s]+ v3` and remove the `RegEx` characters one by one, the proper match is highlighted. If I paste in `[^\s]+ v3`, no matches are highlighted.

**Comment by gskinner** [comment]
Good catch. This was an injection in v3.1. What's happening is that due to some updates in the Explain tool, it's throwing errors when an "applied" token (quantifiers for the most part) follow a `close` token (group or set close). I've fixed this locally, and we should push it shortly.

**Comment by gskinner** [comment]
To clarify: the issue isn't with `[^\s]`, it's with the `+` following a set `[a]`

**Comment by gskinner** [comment]
Pushed an update live. Thanks for finding & reporting this. Please reopen if you encounter it again.

**Comment by koocies** [comment]
Thanks for taking a look at it and thank you for such a great tool!

**Comment by gskinner** [comment]
You're very welcome! Fix deployed.
