### ISSUE TITLE
Error hovering on matches.

### ISSUE THREAD

**Issue by tongjieme** [gskinner/regexr#229]
Reproduce:
https://regexr.com/3hk74
Demo:
![bugs](https://user-images.githubusercontent.com/1511418/33664243-e4478bca-dacd-11e7-936a-ed9e45c15125.gif)

**Comment by gskinner** [comment]
Thanks for reporting this. I've fixed this locally, and it will be in the next update.

**Comment by gskinner** [comment]
Fix deployed.
