### ISSUE TITLE
Can't uncheck expression flag

### ISSUE THREAD

**Issue by wheelerlaw** [gskinner/regexr#230]
## Platform:
Chromium 62.0.3202.94 on Ubuntu 16.04

## Description of behavior:
When I try to uncheck a single expression flag when only a single flag is enabled, it will show as unchecked in the little drop-down, however the flag is not removed from the expression. If I close the drop-down after unchecking the flag, and then re-open the drop-down, it will show as enabled again.

**Comment by gskinner** [comment]
Thanks for reporting this. Fixed locally, and will be pushed live in the next day or two.

**Comment by wheelerlaw** [comment]
Thank YOU for getting the issue resolved in about 5 minutes lol

**Comment by gskinner** [comment]
My pleasure. Fix has been deployed.
