### ISSUE TITLE
Warning for JS lookbehind on Chrome

### ISSUE THREAD

**Issue by Wunder-Wulfe** [gskinner/regexr#233]
*lookbehind* is marked as an error, however it does actually work correctly as noted by the replacement and highlighting
( example: /(?<=\S)\S/g ) 

problem is due to using Javascript 'flavor'
you should make it not work for the javascript version

**Comment by gskinner** [comment]
JS does not support lookbehind in the standard. Chrome does support it though. I'd like to add a warning for this at some point. I'll leave this open to track that.

**Comment by gskinner** [comment]
The error message for this was improved to specify that it doesn't work in all browsers. I'd still like to make this a warning instead of an error at some point.

**Comment by gskinner** [comment]
Closing in favor of #268
