### ISSUE TITLE
Cannot enter expressions

### ISSUE THREAD

**Issue by DocSalvager** [gskinner/regexr#234]
Regexr.com used to work flawlessly with Chromium27 (can't upgrade. don't ask) but now there is no way to enter expressions except by appending to the URL. That of course would require complicated escaping that would make the whole process untenable.

What am I doing wrong?

Attempting to attach a screenshot using "selecting them" link below. No errors reported but nothing showing to indicate success.

**Comment by gskinner** [comment]
It's quite possible that we're using an API or CSS that isn't supported in Chrome 27. We're mainly targeting browsers from the past couple years. Once we get things open sourced again, you're definitely welcome to dig in a bit and see if you can find a quick fix.

Sorry I can't be of more help, but supporting really old browsers is just not a high priority. :)
