### ISSUE TITLE
Non-ASCII characters shift highlights with PCRE

### ISSUE THREAD

**Issue by DGruenwald** [gskinner/regexr#235]
When using the PCRE engine, some characters (presumably all non-ASCII) cause all following highlights to shift forward by one or more characters.
Here's a link and a screenshot: https://regexr.com/3hvod
![regexr](https://user-images.githubusercontent.com/10934467/33944112-6adc6e60-e01b-11e7-828d-5d0aceab6cfa.png)
Matching non-ascii characters itself and the replace tool below seem to be working fine, though.

**Comment by wdamien** [comment]
Nice find!  This has been fixed and pushed live.
