### ISSUE TITLE
Feedback on decision to make regexr closed source.

### ISSUE THREAD

**Issue by wlwl2** [gskinner/regexr#236]
> I'm a firm proponent of open source, but it provided negligible benefits for the project, and formed the foundation for a number of competitive sites, many of which did not open source their own work. This wasn't a requirement by any means, but it created a value imbalance. RegExr will probably be open sourced again in the future, but I am considering releasing it under GPL to encourage people building on it to share alike.

As a maintainer of some sites, I totally understand and support this decision. I think you don't even have to make it open source, just do that on request.

Edit: Sorry, just realized that this was a duplicate of #204

**Comment by gskinner** [comment]
Thanks for the input! Closing in favor of #204.
