### ISSUE TITLE
Special characters explained as "case sensitive"

### ISSUE THREAD

**Issue by CMDJojo** [gskinner/regexr#238]
When I write a character like tab in the regex formula and look at the explanation, it says "Character. Matches TAB characters (Char code 9). Case sensitive". It shouldn't say "Case sensitive" since there is no uppercase/lowercase tab character. This is also the case for lot of other characters too. "½§!"@#£¤$%€&/{([)=}?`'*¨^<>]" are some examples. There could be many more. Please make that message dissappear for characters that does not have different char codes for upper/lowercase

**Comment by gskinner** [comment]
Makes sense. I'll look at whether we can easily add a check for individual characters that don't have cases. The check is simple `char.toUppercase() === char.toLowercase()`, it's just figuring out where it would live.

**Comment by gskinner** [comment]
Fixed: 8a442e260bbfe6585ecca1c49d66264f7a7b6b61
