### ISSUE TITLE
Login: using Github

### ISSUE THREAD

**Issue by TriMoon** [gskinner/regexr#241]
I just wanted to use the login functionality and used the Github option but....
It asks for permission to read my **private email addresses** :scream: 
Can you please change or remove that?! thanks...

**Comment by gskinner** [comment]
We were planning to support the ability to log in to your account via any of the services and using your email address as the key. That way, if you deleted your facebook account (for example), you could still log in with GitHub as long as the email address is the same. This also keeps the door open for us implementing our own account system in the future, and being able to easily merge it.

We don't use or share your email address for anything other than identifying your account.

**Comment by TriMoon** [comment]
Seems i made the right choice of **NOT** using the github login then...
You are able to use anykey to identify accounts, using the email is the worst privacy-wise..
/left user

**Comment by gskinner** [comment]
I’m not sure what anykey is, and a quick search doesn’t bring anything up. Happy to learn more.

**Comment by TriMoon** [comment]
Maybe i should have typed "any key" for the translator to properly translate it...
