### ISSUE TITLE
pasing of ?expression=

### ISSUE THREAD

**Issue by TriMoon** [gskinner/regexr#242]
It doesn't work correctly.
<details>
<summary>javascript to generate url</summary>

```javascript
var base = 'https://regexr.com/?expression='
var uri = '(^\\s*\/\/.*|\\s*[^:]\/\/.*)';
var encoded = encodeURIComponent(uri);
console.log(base+encoded);
console.log(base+decodeURIComponent(encoded));
```
</details>

<details>
<summary>console output</summary>

```console
08:00:42.474 https://regexr.com/?expression=(%5E%5Cs*%2F%2F.*%7C%5Cs*%5B%5E%3A%5D%2F%2F.*) Scratchpad/1:13:1
08:00:42.474 https://regexr.com/?expression=(^\s*//.*|\s*[^:]//.*) Scratchpad/1:14:1
```
</details><hr/>

Using the output of above code to generate the url, try follow these links...
(neither opens correct expression in editor)
  - https://regexr.com/?expression=(%5E%5Cs*%2F%2F.*%7C%5Cs*%5B%5E%3A%5D%2F%2F.*)
  - https://regexr.com/?expression=(^\s*//.*|\s*[^:]//.*)

If one of them does open correct for you, please give feedback saying so.
Then there is a bug in FF-[Container extensions](https://github.com/mozilla/multi-account-containers), and we need to report there :wink:

**Comment by Nightfirecat** [comment]
What behavior are you seeing? I'm seeing what looks like correct behavior in FF57.0.4

![untitled](https://user-images.githubusercontent.com/2199511/35181578-678d6c02-fd79-11e7-9324-f9e7d0e1c86a.png)

**Comment by Nightfirecat** [comment]
The behavior I'm seeing is that the expression picked up by the site in both examples is `^\s*//.*|\s*[^:]/` (missing trailing `/.*`)

**Comment by TriMoon** [comment]
Nevermind it was a bug in my code to generate the url...
New improved version works:
<details>
<summary>javascript to generate url</summary>

```javascript
var base = 'https://regexr.com/?expression='
var re=/(^\s*\/\/.*|\\s*[^:]\/\/.*)/
var uri = re.toString();
var encoded = encodeURIComponent(uri);
console.log(base+encoded);
console.log(base+decodeURIComponent(encoded));
```
</details>

<details>
<summary>console output</summary>

```console
08:32:28.167 https://regexr.com/?expression=%2F(%5E%5Cs*%5C%2F%5C%2F.*%7C%5C%5Cs*%5B%5E%3A%5D%5C%2F%5C%2F.*)%2F Scratchpad/3:14:1
08:32:28.168 https://regexr.com/?expression=/(^\s*\/\/.*|\\s*[^:]\/\/.*)/ Scratchpad/3:15:1
```
</details><hr/>

  - https://regexr.com/?expression=%2F(%5E%5Cs*%5C%2F%5C%2F.*%7C%5C%5Cs*%5B%5E%3A%5D%5C%2F%5C%2F.*)%2F
  - https://regexr.com/?expression=/(^\s*\/\/.*|\\s*[^:]\/\/.*)/

**Comment by TriMoon** [comment]
I just added it to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set#Example2) :rofl:

**Comment by TriMoon** [comment]
Filed bug at bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1431926

**Comment by TriMoon** [comment]
It's been a while and i returned to this issue with a fresh mind.
I now have proof that your code that parses the search string is in fault, especially it's parsing of the **text** parameter...

STR is as follows:
1. Open the link mentioned after the code in https://github.com/gskinner/regexr/issues/242#issuecomment-359156034 eg.: [this link](https://regexr.com/?expression=%2F%28%5E%5Cs*%5C%2F%5C%2F.*%7C%5Cs*%5B%5E%3A%5D%5C%2F%5C%2F.*%29%2Fg&tool=replace&input=%3Cremoved%2F%3E&text=%2F%2F+eslint-disable-next-line+no-unused-vars%0AlockPref%28%09%27keyword.URL%27%2C%09%09%27https%3A%2F%2Fduckduckgo.com%2Fhtml%2F%3Fq%3D%21%2B%27%09%29%09%2F%2F+test)
1. Run the below code in the browser console while on that page.
This code will split the search parameters of the current URL in the browser location bar.
2. Now carefully check the value of the "text" parameter as logged in console and displayed on page, the last part is what's different...
```javascript
for(var pair of (new URL(document.location)).searchParams.entries()) {
    console.debug(pair[0] + ' = \'' + pair[1] + '\''); 
}
```

**Comment by TriMoon** [comment]
Closed the bugzilla bug as invalid, as it is not their fault...

**Comment by gskinner** [comment]
OK. It seems like there might be a couple of problems here. The first, described in the initial report is actually an issue with how the Expression is interpreted. It can accept just a pattern `n+`, or a full expression `/n+/g`. The existing implementation was way too tolerant. I've tightened it up locally and will be posting a fix in the next little while, but if you want to be sure it's always interpreted correctly, you should pass a full expression.

Looking at the text issue, which seems like a separate problem now.

**Comment by gskinner** [comment]
Ok. The Text issue was another dumb mistake. Apparently I was having a bad day when I wrote this functionality. In brief, it was doing a replace with a string as the first param, so it would only replace the first `+` with a space. Fixed locally.
