### ISSUE TITLE
i don't know how to remove repeated lines created from hex please help 

### ISSUE THREAD

**Issue by pop-dahaka** [gskinner/regexr#244]
Hi ,
i have a text file full of lines (0123456789ABCDEF) and most of them are repeated , please help me clean repeated lines , here you're an example for lines : 

`6E6195D78D52
E169E7460048
F8448B88966E
0EA899037C18
78EBB9D558C8
373C95E3F6DF
CB8BF3F10793
C7CC4B4FB0B4
FED6676DFC43
A4943D51F079
17F943292CCF
7EF556D4F7DE
4FBA47C5FDE7
1C8CBAB21BB0
FAF649C7C399
E9F0578E146D
FE92D225519E
DC38C180EFA9
3F996AD5CFDC
9BAE74B1F770
6E6195D78D52
E169E7460048
F8448B88966E
0EA899037C18
78EBB9D558C8
373C95E3F6DF
CB8BF3F10793
C7CC4B4FB0B4
FED6676DFC43
A4943D51F079
17F943292CCF
7EF556D4F7DE
4FBA47C5FDE7
1C8CBAB21BB0
FAF649C7C399
E9F0578E146D
FE92D225519E
DC38C180EFA9
3F996AD5CFDC
9BAE74B1F770`

**Comment by gskinner** [comment]
This is not a forum for RegEx help. It is for reporting bugs or requesting features for RegExr. Check out stackoverflow instead.
