### ISSUE TITLE
Bug: lookaheads with character sets misidentified

### ISSUE THREAD

**Issue by kennethgillen** [gskinner/regexr#245]
Multiple consecutive lookaheads with character sets inside are misidentified as a `posixcollseq` when REGEX format `PCRE` chosen:

e.g.: `(?#KB)\b\d{1,3}(?<!@\d)(?<!@\d\d)(?=(\d{3}([ \t\r\n\f\.\/\\\b\-\:]|$)))(?# not followed by datestrings common in filenames)(?!\d*[a-zA-Z\-])(?!\d?\d?01[3-8])(?!\d{3}\.\w)(?!0?1[3-8](0[1-9]|1[0-2])(0[1-9]|[1-2]\d|3[01])(([01]\d|2[0-3])[0-5]\d)?)(?!\d* HTTP)(?!06[34])`

**Comment by kennethgillen** [comment]
Same for the following:

`(?# BASH 1: var)\$[^││┤\-\|\">\)\(\s\\\/\}\{\[\]]+(?=[\">\(\)\s\\\/\}\{\]\[])|(?<=for )\s*[^\s]+(?=\s+in\b)|(?<=while read )[^\s]+\b`

![screen shot 2018-01-29 at 13 52 25](https://user-images.githubusercontent.com/2727871/35513685-c6d2e190-04fb-11e8-9846-aeb148bc1298.png)

Regexr seems to be parsing the `\]`which should be an escaped character in the set inside the lookahead.

**Comment by gskinner** [comment]
This should be fixed with the next update. See: #253

**Comment by kennethgillen** [comment]
Thanks!
