### ISSUE TITLE
[OFF TOPIC] RegEx works fine (and only) in RegExr

### ISSUE THREAD

**Issue by jvitoroc** [gskinner/regexr#246]
I know that this is not the right place to ask such questions, but something odd is happening here:
When I use the RegEx in JavaScript, it only returns null: https://jsfiddle.net/
In RegExr works fine: https://regexr.com/3jnlt   https://pastebin.com/TkkFLXvN

Sorry for my english

**Comment by gskinner** [comment]
Your JSFiddle link didn't come through, but RegExr runs the pattern in your browser, so if it runs in RegExr it is running correctly in JS.

However, there are lots of ways to run RegEx in JS, and you may get different results depending on which method you use. RegExr uses `RegExp.exec()` for most things, so it's worth starting there.

`/(foo)/i.exec(str)`
