### ISSUE TITLE
Negative lookbehind seems to work - but RegEx warns me?

### ISSUE THREAD

**Issue by larsnaesbye** [gskinner/regexr#247]
When trying out 

`(?<!\.)(\b(?:src|href|url)\b[=\(]?[\"\']?)(\w|\.\/)(?!ttps?:\/\/)
`
for a URL part match, I get a warning that negative lookbehind is not supported in this flavor of RegEx. But it nicely matches my test results, e.g. it matches `url(./Folder/File.ext)` and doesn't match `.url(r)`

So it has helped me a lot - thank you for RegExr. Just thought you'd like some appreciation, and if the error message is right I'd like to know why :-)

**Comment by gskinner** [comment]
I'm guessing this is in Chrome with the JS engine selected? If so, this is because negative lookbehind is not supported in the JS spec, but Chrome does support it. We throw an error since it won't work in most browsers. I'll look at improving the error message for this specific scenario.

**Comment by larsnaesbye** [comment]
Yes, I was using Chrome :)

**Comment by FerrusDude** [comment]
Negative lookbehind is included in the ES2018 spec. 
Since _eventually_ it will work, maybe include a note to this effect in the error?

https://tc39.github.io/ecma262/#prod-Assertion

**Comment by gskinner** [comment]
I've updated the error for this particular case to say:
The "negative lookbehind" feature may not be supported in all browsers.

Fixed locally.
