### ISSUE TITLE
Regexr v 3.1 refreshes page randomly

### ISSUE THREAD

**Issue by neptunecentury** [gskinner/regexr#248]
I'm not sure what is triggering it, but I think it seems to happen when a tooltip explanation is displayed. Basically, the whole page will refresh and wipe out all text and expressions. It happened to me twice in less than 5 minutes time. I am using Edge browser.

I can usually get it to happen by just hovering over the expression box, and when the tooltip appears, it will hang for a second then refresh. After 3 or 4 times, Edge then displays a message saying:
"This page is having a problem loading"

EDIT: It seems to only happen when I move the cursor over the tooltip, just showing the tooltip doesn't cause it.

**Comment by wdamien** [comment]
If there was a prize for bizarre bugs bugs found @neptunecentury you have it. This is definitely an Edge bug, I was able to make a simplified repo here: https://codepen.io/pixelscript/pen/XZXyVY .. Just roll over the text, and out over the black square.  This crashes Edge every-time.  But only if the second element is svg, and its being removed from the dom at the same time.

Knowing this we can atleast figure out a work around this crasher bug.

My current edge version is:
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

**Comment by gskinner** [comment]
is this still an issue in newer versions of Edge?

**Comment by neptunecentury** [comment]
I just tried it, and I did not see this happening. So it may not be an issue anymore. I'll comment here again if I see it again.

**Comment by gskinner** [comment]
Great. Closing for now. Please reopen if it's still an issue.
