### ISSUE TITLE
Backslashes (\) in Text disappears when Saving

### ISSUE THREAD

**Issue by hpoul** [gskinner/regexr#250]
When entering backslashes into the "Text" field and hitting Save, they disappear..

e.g. `test \ test` becomes `test  test`

![regexr-disappearing-backslash](https://user-images.githubusercontent.com/313066/37295800-5c33065a-2619-11e8-9709-61c740b75656.gif)

**Comment by wdamien** [comment]
Thanks! I just pushed a fix for this. Patterns were saving correctly, just not returning correctly. Now you'll get back whats saved.
