### ISSUE TITLE
Support for Unicode Regular Expressions missing

### ISSUE THREAD

**Issue by BenjaminHoegh** [gskinner/regexr#251]
Missing the support to use `\\p{L}` and other Unicode regex validators

> Note: PHP accept `\pL`

[www.regular-expressions.info](https://www.regular-expressions.info/unicode.html)

**Comment by gskinner** [comment]
I'm not sure I understand. RegExr supports both of those syntaxes in the PCRE engine. Can you please elaborate and reopen?

![screen shot 2018-03-12 at 4 44 23 pm](https://user-images.githubusercontent.com/157128/37313402-a8abdaac-2614-11e8-8272-cdb050b8299e.png)

**Comment by BenjaminHoegh** [comment]
Well that's weird, tried to use them yesterday and it didn't work
