### ISSUE TITLE
Should look behind be supported?

### ISSUE THREAD

**Issue by koocies** [gskinner/regexr#252]
Tried the following regex and got an error saying that look behind is not supported in this flavor of regex
(\d+)(?<!10)
I've tried it in other regex tester that use PCRE standard an it does work.
Just to note look ahead does work.

**Comment by wdamien** [comment]
Hey @koocies you can find more details at #247 .  Basically look behinds are not fully supported in browsers yet, but it is coming.

**Comment by gskinner** [comment]
And to clarify - lookbehind is supported if you switch to use PCRE in RegExr instead of JS.

**Comment by koocies** [comment]
Thanks! Sorry, I should have looked to see if this was already reports. Thanks for the response!
