### ISSUE TITLE
False Positive Error "posixcollseq" feature is not supported in this flavor of RegEx

### ISSUE THREAD

**Issue by jarrodhroberson** [gskinner/regexr#253]
This pattern is causing an error to be shown incorrectly.

^([0-9]{4})-(0[1-9]|1[012])-([012][0-9]|3[01])$

Here is the link

https://regexr.com/3mat2

**Comment by gskinner** [comment]
I've created a simpler test case:
https://regexr.com/3qikj
`([0])-([0])`

**Comment by gskinner** [comment]
Good catch. I've made the pattern to catch POSIX collating sequences much more strict. Fixed locally.

There is still one edge case, which I may fix in the future:
`[.\].]`
