### ISSUE TITLE
Patterns with long expressions can cause incorrect layout in Firefox

### ISSUE THREAD

**Issue by wdamien** [gskinner/regexr#258]
See in Firefox: 59

You can see the selected pattern pushes out the width of community list.

![firefox_2018-04-20_11-31-33](https://user-images.githubusercontent.com/299050/39067674-67387772-448e-11e8-85ef-193f834b6a82.png)

**Comment by gskinner** [comment]
Fixed: 8ffc9aec7a9a0107a1c276347df98e0e9eebc46c
