### ISSUE TITLE
Community pattern preview not showing whole pattern

### ISSUE THREAD

**Issue by trevordunn** [gskinner/regexr#260]
Steps:
1) Search for "All HTML tags" in the Community patterns and select the first one (description is "Complete and bullet-proof HTML tags detection...")
2) Notice the preview says "/\s]+))?)+\s*|\s*)/?>/g"
3) Load the full pattern.
4) Notice the pattern in the input is "/</?\w+((\s+\w+(\s*=\s*(?:".*?"|'.*?'|[^'">\s]+))?)+\s*|\s*)/?>/g"

**Comment by gskinner** [comment]
Fixed locally.
