### ISSUE TITLE
negate alternation

### ISSUE THREAD

**Issue by realgeek** [gskinner/regexr#261]
https://regexr.com/3q9b4

I found an example of this regex on https://stackoverflow.com/questions/406230/regular-expression-to-match-a-line-that-doesnt-contain-a-word and tried it against 'grep -P' which correctly shows everything but PyCon. RegExr shows no match.

**Comment by gskinner** [comment]
Hi @realgeek - you need to enable the `m`ultiline flag, so that `^` and `$` match on the start and end of lines instead of BOF and EOF. With that change, it works as expected.
