### ISSUE TITLE
Proper escaping of reserved character {

### ISSUE THREAD

**Issue by rsrsl** [gskinner/regexr#277]
### Observed Behavior
Using `/begin{theorem/g` on
```latex
\begin{theorem}
  $A=b$
\end{theorem}
```
matches the reserved character `{`.

### Desired Behavior
The matching regex should have been  `/begin\{theorem/g` according to the [reference](https://github.com/gskinner/regexr/blob/8bca1f22fd9a5b9639201bbc2880ed30606ed9d2/dev/src/docs/reference_content.js#L285).

**Comment by gskinner** [comment]
Hmm. I guess we could tweak the wording. You should escape `{`, but you don't strictly have to. Maybe we could divide them in the description into two categories, those that _must_ be escaped, and those that _should_  be (ex. `{ } / ]`).

I'll leave this open and consider a description tweak.

**Comment by rsrsl** [comment]
Yes I see the problem with `{`: some flavors of regex allow unescaped open braces while others don't (for instance, Java, `std::regex`, and Boost do not allow for unescaped unmatched curly braces). I take back my statement, maybe a revision of the reference is in order :+1:

**Comment by gskinner** [comment]
Rather than overcomplicate this, I'm just going to soften the language a bit to "_should_ be preceded" instead of "_must_ be preceded".
