### ISSUE TITLE
Asserts incorrectly treated as escaped characters

### ISSUE THREAD

**Issue by iamdriz** [gskinner/regexr#278]
This regex: `\A[0-9]{4}\z` when tested on regexr are showing that `\A` and `\z` are Escaped characters meaning that it expects the string to start with an A and end with a z.

However this is incorrect as `\A` asserts the position at the start of the string and `\Z` at the end.

Tested here: https://regexr.com/3tpf7

You can see it working correctly on another regex site here: https://regex101.com/r/CzCkdJ/1

**Comment by gskinner** [comment]
Your test is using the Javascript engine, which does not support `\A` or `\z` asserts (it treats them as escapes). If you switch the engine to PCRE, you will see the behaviour you describe.

https://regexr.com/3tpg5
