### ISSUE TITLE
Session grtting crash

### ISSUE THREAD

**Issue by priyanka-boggavarapu** [gskinner/regexr#279]
When we are pasting thousands of strings and writing one pattern to match all those string, the site is getting crashed. Please suggest me any solution.

**Comment by gskinner** [comment]
Can you provide more info?

- how many characters are in the Text you are searching against?
- what pattern are you searching for?
- what engine are you using (JS or PCRE)?
- what browser?
- what specifically do you mean by crashed? Browser crashing? Errors in the console? Errors in the UI?

Thanks. Please reopen when you provide additional info.
