### ISSUE TITLE
Zero width matches produce an error

### ISSUE THREAD

**Issue by bkiers** [gskinner/regexr#28]
Zero width matches, like  `(?=b)`, give an error saying that there are an infinite amount of matches for them (which is not true, of course).

**Comment by connec** [comment]
A 0-length regex is perfectly valid and can very useful.  Iterating through the matches is also not difficult:

```js
// Find positions for commas in a number (e.g., 12,345,678 -> 2, 5)
var s  = '12345678'
  , re = /\B(?=(?:\d{3})+(?!\d))/g
  , m;
while(m = re.exec(s)) {
  console.log('match at', m.index);
  if(m[0].length == 0 && ++re.lastIndex > s.length)
    break;
}
```

I've made a pull request that implements this, along with some naive highlighting.
