### ISSUE TITLE
SQL Injection Problems across the board

### ISSUE THREAD

**Issue by jbis9051** [gskinner/regexr#287]
Theres many instances of SQL injection.  The following function is used to sanitize

[regexr/server/core/DB.php](https://github.com/gskinner/regexr/blob/master/server/core/DB.php):

```
    public function sanitize($value) {
        if (is_null($value)) {
            return '';
        }
        if (is_string($value)) {
            return $this->mysqli->real_escape_string($value);
        } else {
            return $value;
        }
    }

```

`real_escape_string()` is not enough to prevent SQL Injection or any function for that matter.

https://stackoverflow.com/questions/5741187/sql-injection-that-gets-around-mysql-real-escape-string

All values should be sent as parameters in a prepared statement.  I will make a pull request soon fixing it.

**Comment by hakre** [comment]
Any ETA on the PR?

And what function is this about? How does (in context of the application) quoting of the database value is currently done? So for it looks to me that this (unspecified) function's code excerpt is not about quoting, so your report could benefit greatly from more details here IMHO.

**Comment by jbis9051** [comment]
@hakre Not sure. But shouldn't be too long. It's easy to fix.

See edit for the function.

And I am not exactly  sure what the following means

> How does (in context of the application) quoting of the database value is currently done?

Heres an example of the vulnerable code but its all over the PHP code.

https://github.com/gskinner/regexr/blob/master/server/actions/account/login.php:

`$this->db->query("UPDATE users SET email='$email', type='$type' WHERE id='$sessionData->userId'");`

**Comment by hakre** [comment]
@jbis9051: thanks, let me know if you can do a better estimation than "not too long" for an "easy to fix" which looks like is 8hrs+.

For the example you give, what has that to do with the code-fragment you have in the OP?

Don't get me wrong, a new feature like using prepared statements might not be wrong at all, but what has that to do with the bug you report? Not that you solve x with y. There is either a concrete problem that should be addressed with a fix (and looks like you've found something) but that is different to suggest using prepared statements (even if that has a positive side-effect).

Session data needs to be considered as user-input (as well as data returned from the database) so these values are not to be trusted in any shape or form.

**Comment by jbis9051** [comment]
@hakre  Yeah, after looking through the code more carefully, it may take a while to do. 

 To prevent sql injection the function `sanitized` is used on many of the elements. Its a two part problem under SQL Injection

1. Sanitization function does sanitize properly
2. User input is put directly into SQL statements

**Comment by jbis9051** [comment]
@hakre  Also may need some help, don't full understand how everything is implemented.

**Comment by hakre** [comment]
I can imagine a third problem:

3. Sanitization Function is used on User Input but values are used unquoted to build the SQL statement string..

I would start with tackling the concrete flaws, that is learning about how to detect places of 2. and provide first patches.

Also the sanitization function needs a test-case and then the good and the borderline values need to be used to make it more robust. This could be an additional patch.

I would start this way especially as the code base is new to you so you get more accustomed to it.

Additionally the smaller patches are easier to review so you should get feedback faster form the project itself. I'm just a bystander who noticed your report.

**Comment by jbis9051** [comment]
For example:

```
 $stmt = $conn->prepare("UPDATE users SET email=?, type=? WHERE id=?");
            $stmt->bind_param("sss", $email, $type,$sessionData->userId);
            $stmt->execute();
```

**Comment by jbis9051** [comment]
@wdamien Prefectly said. 

I have started to change everything over but I don't like how I am doing it. Gonna look into a better way. Will post back with more details soon.

**Comment by jbis9051** [comment]
I was thinking something like this:


```
 /**
     * Based on query function from here -> https://github.com/WebsiteBeaver/Simple-MySQLi/blob/master/simple-mysqli.php
     *
     * @param array $values (optional) Values or variables to bind to query. Can be empty for selecting all rows
     * @param string $types (optional) Variable type for each bound value/variable
     * @return $this
     * @throws mysqli_sql_exception If any mysqli function failed due to mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT)

     */
    public function query(string $sql, $values = [], string $types = '') {
        $mysql = new \mysqli(DB_HOST, DB_USER_NAME, DB_PASSWORD, DB_NAME);

        if(!is_array($values)) {
            $values = [$values]; //Convert scalar to array
        }

        if(!$types) {
            $types = str_repeat('s', count($values)); //String type for all variables if not specified
        }
        if(!$values) {
          $stmtResult = $mysql->query($sql); //Use non-prepared query if no values to bind for efficiency
        } else {
            $stmt = $this->stmt = $mysql->prepare($sql);
            $stmt->bind_param($types, ...$values);
            $stmt->execute();
            $stmtResult = $stmt->get_result();
        }
        return $stmtResult;
    }
```

**Comment by wdamien** [comment]
Great start. I would want to keep the current `db->connect()` method, so we can re-use the connection in the same session. Theres also the result handling that currently exists in query. But for the handling of the new query execution 👍 👍

**Comment by jbis9051** [comment]
I forgot about this :( Gonna try to finish this up soon.

**Comment by wdamien** [comment]
@jbis9051 Thanks for your interest in this.  I hate to squash any work you've already done, however I found some time recently to switch over to use `prepare`.  Its not live yet, but is WIP in https://github.com/gskinner/regexr/tree/tests (tests refers to a new RegExr feature, and switching the server over made sense while making those new additions).

Any feedback you have there is definitely appreciated.  I took a slightly different approach, choosing to merge the values and data types into a single param, instead of using 2. For example the new `execute` (aka the old `query`) calls look like this:

```
$this->db->execute($sql, [
   ["s", $patternId],
   ["s", $foo],
]);
```

**Comment by jbis9051** [comment]
@wdamien Great! Glad you found a solution. I will take a closer look soon.

**Comment by wdamien** [comment]
The change to use prepared statements is finally complete, and now live on regexr.com.

**Comment by jbis9051** [comment]
Awesome!
