### ISSUE TITLE
backslash should be forward slash

### ISSUE THREAD

**Issue by gohassgo** [gskinner/regexr#297]
The RegEx Reference > Flags incorrectly notes backslash instead of forward slash.

"Flags follow the closing **backslash** of the expression (ex. /.+/igm )."

https://github.com/gskinner/regexr/blob/c8ce2a8bdf26bc10c9abe11f613bc537c72b0f40/dev/src/docs/reference_content.js#L638

**Comment by gskinner** [comment]
Good catch. I've fixed this locally, and it will be included in the next update.
