### ISSUE TITLE
feature request: user test suite

### ISSUE THREAD

**Issue by Glutnix** [gskinner/regexr#298]
Rather than turn on `\m` which has some unintended side effects, it would be good to have the ability to add some lines of text I expect to match, and some that I wish to fail. For a replace, the tests should also support intended replace output

**Comment by rafegoldberg** [comment]
@Glutnix not sure if you've seen the updates since last year, but you asked @gskinner delivered!

![image](https://user-images.githubusercontent.com/886627/80609513-04435f00-89ed-11ea-88ea-d02f6f8bc8fa.png)

**Comment by gskinner** [comment]
Your wish is my command. :)
