### ISSUE TITLE
Missing `id` in reference of `match any`?

### ISSUE THREAD

**Issue by skys215** [gskinner/regexr#305]
Hi, 
   I found that `match any` has no `id` attribute.
   Is it removed on purpose? Or deleted it accidently?

https://github.com/gskinner/regexr/blob/c776596a886644798058ecc8ea296c27e75921b9/dev/src/docs/reference_content.js#L78

Thank you.

**Comment by gskinner** [comment]
That's an easy fix. Thanks for bringing it to my attention!

**Comment by gskinner** [comment]
Fixed locally. Will be in the next version.

**Comment by skys215** [comment]
By the way, some of the item has no `label` attribute and seems that it uses the `id` attribute.
Is it because label is same as id, so it is possible not to write it repeatedly as `label`?

**Comment by gskinner** [comment]
Yes. That’s exactly correct. It uses id as the label if it isn’t defined.

**Comment by skys215** [comment]
I see.
Because I'm [translating to other language](https://github.com/gskinner/regexr/issues/37#issuecomment-469093228) and it's quite ready to deploy on the net.
