### ISSUE TITLE
Highlighting the longest match / Input field behavior

### ISSUE THREAD

**Issue by Sxubas** [gskinner/regexr#309]
Hi, I was trying this regex: `/([0-9]{6}|[0-9]{8})(,( )*([0-9]{6}|[0-9]{8}))*/` which is a simple validation for a list of numbers of length 6 or 8.

Trying it on regexr, I used the test string: `'12345678'` and only the first 6 characters got highlighted but the last two did not. This lead me to think that my regular expression was not correct to what I was trying to achieve. However testing it on a input's 'pattern' attribute indeed passes the strings I tested against.

My suggestion is to add a way to highlight the longest string that matches a regex or a way to test the regex as an input's attribute 'pattern' would do.

**Comment by gskinner** [comment]
I believe that the input pattern in essence forces a match against the full string. You should be able to replicate this by adding start / end anchors (`^` / `$`) to your pattern.

For example:
https://regexr.com/4be10
