### ISSUE TITLE
No matches for a simple regex

### ISSUE THREAD

**Issue by birdie-github** [gskinner/regexr#311]
Here's a regex:

```^(5\.1)$```

Now if you type ```5.1``` in a separate line with or without a new line at the end in the text to match, it won't be found/matched.

**Comment by Nightfirecat** [comment]
I didn't reproduce this in a minimal case: https://regexr.com/4dfdm

**Comment by lannymcnie** [comment]
Here is another case with multi-line. Performs as expected.
regexr.com/4dfds

**Comment by birdie-github** [comment]
Looks like the **m** flag is required 'cause otherwise it doesn't work: regexr.com/4dg7o

**Comment by Nightfirecat** [comment]
If you hover over the `^` or `$` characters, you'll see why:

> **Beginning.** Matches the beginning of the string, or the beginning of a line if the multiline flag (**m**) is enabled.
