### ISSUE TITLE
incorrect match

### ISSUE THREAD

**Issue by PrestonTaylor** [gskinner/regexr#319]
expression used
` (blah[A-z0-9 )>.<(-]*#)`

text used 

    [local]blah#conf
    [local]blah(ipv6 acl default_acl6)#
    [local]blah(config)#
    [local]blah(config)#
    [local]blah(context local)#

This matches all lines but should not match the second line as far as I can tell because the regex has no _ (underscore) character match

**Comment by Nightfirecat** [comment]
`A-z` matches characters of codes between 65 and 122 (inclusive)

![character_codes](https://user-images.githubusercontent.com/2199511/61397161-d1463980-a8b8-11e9-9855-5215bcc52a34.png)

Underscores are character code 95

![underscore_character_code](https://user-images.githubusercontent.com/2199511/61397200-de632880-a8b8-11e9-868b-3b1ad35b2cf2.png)

Changing your regex to `(blah[A-Za-z0-9 )>.<(-]*#)` makes it match as you expected.
