### ISSUE TITLE
Support other RegEx flavours.

### ISSUE THREAD

**Issue by gskinner** [gskinner/regexr#32]
It would be nice to support other RegEx flavours. This is a major task, requiring a number of different enhancements:
- UI for selecting a flavour and conveying info about it.
- The lexer classes would need to support some kind of feature map to enable / disable features in syntax highlighting (and of course be updated to support a ton of new tokens).
- Similarly, the reference would need to hide or clearly mark unsupported features (and documentation would need to be added for the new tokens)
- The engine and UI would need to be updated to support modular "solution" engines, which could be synchronous (client-side: JS, AS3), or asynchronous (server-side: PHP, perl, ruby, etc).

For now, this issue will just be a place to brainstorm approaches, and identify challenges.

**Comment by isonno** [comment]
Would love to see support for Python's RegEx.

**Comment by ivangretsky** [comment]
This is very useful feature. I've seen it implemented [here](https://regex101.com).

**Comment by weitzhandler** [comment]
Any progress?

**Comment by gskinner** [comment]
Anyone following this issue, may be happy to see the work going on in the new flavours branch:
https://github.com/gskinner/regexr/tree/flavours

Still early, but it's coming together fairly quickly, and I'm committed to getting it done. We have roughed in PCRE support (mostly just for our own testing at present), and got about half the work done for updating the lexer. I'll try to update here as new things roll in.

**Comment by gskinner** [comment]
Supported in v3.0

**Comment by gskinner** [comment]
v3.0 has full support for PCRE, and an extensible model for adding other flavors.

I think our next target with be XRegExp (see #110), since it's an easy win that doesn't require server support, and then we'll look at the potential for other server based flavors.

**Comment by YKubi** [comment]
> Anyone following this issue, may be happy to see the work going on in the new flavours branch:
> https://github.com/gskinner/regexr/tree/flavours
> 

The link is broken 😞 .
Would love to see support for **.Net** RegEx.
