### ISSUE TITLE
[Improvement] Option for matching the regex agains every new line

### ISSUE THREAD

**Issue by leftdevel** [gskinner/regexr#333]
Hi there. Awesome project.

It would be great if the regex could be ran against each new line in the text area similar to other online tools (though I still prefer this one by far of course).

Currently the regex is applied to the whole content of the text, which makes sense, but would be great to optionally match against different strings in order to make sure it works for multiple scenarios.

Thanks.

**Comment by i3li** [comment]
It is already supported. Enable the 'multiline' flag from the top right corner :)

<img width="217" alt="Screen Shot 2020-01-14 at 6 16 03 PM" src="https://user-images.githubusercontent.com/21133646/72356234-f72e8880-36f9-11ea-91cc-9faf932a5fc7.png">

**Comment by steltenpower** [comment]
So every line of text is then looked at as a separate string?
Would it then make sense to have a subtle divider between those lines of text, maybe a pixel thick lightgrey line?

**Comment by leftdevel** [comment]
Awesome, thank you!
