### ISSUE TITLE
$ doesn't work for matching line end when using javascript engine.

### ISSUE THREAD

**Issue by zhangchf** [gskinner/regexr#334]
With javascript engine, $ doesn't work, no matches when trying to match line end.
But after switch to PCRE engine, it works.

**Comment by Nightfirecat** [comment]
Do you have the `m`ultiline flag enabled? Notice that this regexr has two matches with it enabled, but only one with it disabled (since it is then checking the full text rather than each line): https://regexr.com/4s12p

**Comment by zhangchf** [comment]
I see, thanks.
I had an extra blank line after my sample string. Thanks for the explanation.
