### ISSUE TITLE
Clipboard broken in Firefox

### ISSUE THREAD

**Issue by camgaertner** [gskinner/regexr#344]
Clipboard, Ctrl+A, and Ctrl+Left/Right seems to be broken in Firefox

```
❯ firefox --version
Mozilla Firefox 72.0.1
```

Hard to explain without a video, but let me know if more info is needed.

**Comment by Nightfirecat** [comment]
I can't reproduce this on Firefox 72.0.2. Can you reproduce this in Firefox safe mode? (that is, with all add-ons disabled)

**Comment by camgaertner** [comment]
In safe mode, I don't have the issue. Thanks for your patience. Must be on my end somehow.
