### ISSUE TITLE
Google login not working

### ISSUE THREAD

**Issue by govindap11** [gskinner/regexr#349]
Hi!
Today as I tried to login using my Google account, just like any other day, it asked for permission to access my email addresses. Weird, I thought. Granting it permission, I proceeded hoping to get logged in and view my saved patterns. But I never get logged in.
Anything changed in the past few days concerning Google login?

**Comment by gskinner** [comment]
Thanks for the heads up! We quietly rolled out a v3.8 build, which adds some new features, but it looks like it causes some auth problems. I rolled it back to v3.7 for now, and we'll try to pin down what went wrong.
