### ISSUE TITLE
Unicode matching is inconsistent with other PCRE evaluators

### ISSUE THREAD

**Issue by Denubis** [gskinner/regexr#357]
Demonstration: https://regexr.com/53ruv

Regex: `s/〚[^〛]+〛/` should match both `〚γ̣υ̣ν̣ά̣〛` and `〚—〛` but only matches the first. When tested with a different PCRE evaluator (R), it worked correctly.

Cheers!

**Comment by gskinner** [comment]
Interesting. We execute the RegEx on `PHP 7.3.11 and PCRE 10.32 2018-09-10`, so it's not RegExr per se, but rather the specific PCRE implementation. I double checked, and it looks like it's not an issue with character encoding to or from the server, so unfortunately it looks like there's not a ton we can do to address this. I'm open to additional thoughts though.
