### ISSUE TITLE
Disable Replace pane for JavaScript regular expressions if the g flag is used

### ISSUE THREAD

**Issue by jdgregson** [gskinner/regexr#376]
In JavaScript, capture groups are ignored if the `g` flag is used in the expression, and only the full match is returned. However, capture groups and the Replace pane continue to work in RegExr when the `g` flag is used. This caused me to spend a bit of time trying to get an expression which worked in RegExr to return capture groups in the browser.

RegExr should disable the Replace pane and provide a helpful explanation when the `g` flag is used in JavaScript mode, or at the very least provide some kind of a warning.

**Comment by gskinner** [comment]
I'm not sure where you're getting that info, but it's incorrect. Here's a simple test:

`console.log(/a(b)c/g.exec("abc")[1]); // returns "b"`

To be clear - we execute the regex in your browser, so the results you get are what the browser supports.

**Comment by jdgregson** [comment]
Ahh, this appears to only be an issue when using the `String.prototype.match()` method to evaluate regular expressions on a string:

    "abc".match(/a(b)c/); // returns ["abc", "b"]
    "abc".match(/a(b)c/g); // returns ["abc"]

That is more of a issue with the `String` library than anything else.
