### ISSUE TITLE
Test cases with russian chars don't save correctly

### ISSUE THREAD

**Issue by JaoodxD** [gskinner/regexr#387]
Test cases works fine until I try to save them. After saving every russian (cyrillic) symbol replaces with ? (question mark).

P.S. If it's necessary need here is the list of steps to reproduce the issue:
1. Create new regexp.
2. Go to "Tests" tab.
3. Create test-case with cyrillic symbols.
4. Click on "Save".
5. Here it is. Every cyrillic symbol has replaced with question marks except for those contained in regular expression itself.

**Comment by wdamien** [comment]
Thanks for the report! This has been fixed. Unfortunately any previous Cyrillic characters are lost, but going forward they'll save fine.
