### ISSUE TITLE
This should have 2 matches, it only gets one

### ISSUE THREAD

**Issue by dorusan** [gskinner/regexr#400]
This should trigger 2 matches on the specified string, it only gets one trigger on the first group:
RegEx: ([0-9a-fA-F]{2}){5}
Test string: FFFFFFFFFFFFFF FFFFFF FFFFFFFFFFFF

**Comment by chucklu** [comment]
@dorusan  It works as expected
![image](https://user-images.githubusercontent.com/3004057/112265106-e1790380-8cac-11eb-887d-a0a800cbb80d.png)

**Comment by dorusan** [comment]
Thx for fixing it, it didn't work back then
