### ISSUE TITLE
[^\$] not working  

### ISSUE THREAD

**Issue by alexkorpas** [gskinner/regexr#409]
Greetings,

I was trying to make some regexp in a latex document to detect some strings that are not in math mode. For example, let's say I want to select all the strings `test` but not the `$test$` ones. I crafted the regular expression `/[^\$]test[^\$]/gm` and tested the website, but it doesn't work. However, when I used it in my project it worked as intended.

You can find some tests [here](https://regexr.com/5s6ie), so you can see yourself.

**Comment by gskinner** [comment]
That looks like it's working as expected. Your second test isn't matching because it doesn't have any characters to match `[^\$]`. For example, `XtestX` will match.

**Comment by alexkorpas** [comment]
Oh right, the proper way to do what I was intended is to use a negative look-ahead before and after the `test`. Thank you and sorry for the misinterpretation.
