### ISSUE TITLE
Issues with save after long periods of editing

### ISSUE THREAD

**Issue by tomByrer** [gskinner/regexr#42]
I was about to save, got stuck on the tag-bug #41, & lost all my work, reverting to an earlier save.
related: https://github.com/gskinner/regexr/issues/22
Not sure how to re-trace steps, but seems to be a timing thing?

**Comment by gskinner** [comment]
I expect this will be resolved in v3.0, as all this functionality is being rewritten.

**Comment by gskinner** [comment]
This should be resolved in v3.0. Please reopen if not.
