### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by Tibinsunny** [gskinner/regexr#420]
Hi there,
Hope you are doing good  :-D 
A potential security issue was identified in this project and has been reported to you through huntr.dev. Please find a detailed report of the vulnerability [here](https://huntr.dev/bounties/1-gskinner/regexr/).

The link is private, and will be only accessible to the project maintainers. Feel free to mark the report as valid, if you find it is.

Thanks!

**Comment by gskinner** [comment]
Thanks @Tibinsunny - this has been confirmed and fixed in 3b50b080914295b33084e9ad07730f3459f0ca70

Really appreciate the report!
