### ISSUE TITLE
Auto-save

### ISSUE THREAD

**Issue by tomByrer** [gskinner/regexr#43]
Would help prevent the sting from #42 & #41

**Comment by gskinner** [comment]
We're not specifically doing auto-save in v3.0 (and I'm not sure we ever will), but we are adding an indicator for unsaved changes, and plan to wire up cmd/ctrl-s saving.

**Comment by gskinner** [comment]
As per the above, ctrl / cmd S and save state indicators are in v3.0

It's not auto-save, but hoping this is close enough.
