### ISSUE TITLE
Tab crashes whenever clicking on a community pattern in the list

### ISSUE THREAD

**Issue by benknight** [gskinner/regexr#461]
Tested on latest Chrome and Edge browsers on macOS latest.

**Comment by trevordunn** [comment]
@benknight I can't reproduce. I'm using Chrome `102.0.5005.61` on macOS `11.6.6`. Clicked a bunch of community patterns and no crash. I even tried clicking the arrows to move the expressions and text into the main editor. Can you try again and post some more specific repro steps if you're still getting a crash?

**Comment by benknight** [comment]
Seems like everything's working fine!
