### ISSUE TITLE
Failing result in a particular Regular Expression

### ISSUE THREAD

**Issue by luisalbertomendez** [gskinner/regexr#472]
Hi there, I am evaluating the next RegEx in your website: _a*(ab|b)*_
Doing by hand (Thompson methodology) and checking with your algorithm, the string "aba" is not a valid one, but your website is marking as a good one.
![image](https://user-images.githubusercontent.com/104271487/187104182-3da1b2af-436a-45b2-b551-6ebb24927c09.png)
![image](https://user-images.githubusercontent.com/104271487/187110764-59748f22-bf30-4ec4-afe6-464a9c669604.png)
Well, I don't know if  this comment will have any impact, but I left here my two cents!
Regards,

**Comment by gskinner** [comment]
Per your screenshot, it is not matching "aba", it is matching "ab" and "a". You can confirm this by looking at the grey highlight that encloses the full match, or by hovering over the match to see info.
![image](https://user-images.githubusercontent.com/157128/187246201-6513f13e-b747-4aa4-8ad8-3445e6a7c318.png)

**Comment by luisalbertomendez** [comment]
Thank you for answer and sorry about missing this detail!
