### ISSUE TITLE
Feature request: load expression snippet from query

### ISSUE THREAD

**Issue by dank8** [gskinner/regexr#479]
please consider adding a url query option for smaller snippets of text and expressions

Text:
"sessionId":"Edhgjhsbdjkkmsdsd-dlkmsdl.Mkhsdiufhskjndjsbsbd.iusdhfjsnkdnsd"
expression:
(\.+?).(\.+?).(\.+?)

`https://regexr.com/?pattern=(.%2B%3F).(.%2B%3F).(.%2B%3F)&text="sessionId"%3A"Edhgjhsbdjkkmsdsd-dlkmsdl.Mkhsdiufhskjndjsbsbd.iusdhfjsnkdnsd"`

**Comment by gskinner** [comment]
This already exists. Check out Help > Query String Support

Let me know if that doesn't do what you need.
