### ISSUE TITLE
Save (Ctrl+S) feature doesn't work in some cases

### ISSUE THREAD

**Issue by edoardo-molinatti** [gskinner/regexr#480]
The save feature doesn't work in some cases.
- I have 25 saved patterns in "My Patterns"
- It always worked until this moment (so I'm not sure if it could be due to a regression in a recent update or it's just a bug)
- I had an error (still visible in the screenshot) at the moment of the save in the regex (a forward slash not escaped).
  ⚠️ In this case, I'd say it's better to point out the error to the user, instead of just not saving the pattern.

When pressing the Save button nothing happens, as well as when pressing the keyboard shortcut Ctrl + S.
This is what I see when trying to save an invalid pattern in my account:
![image](https://user-images.githubusercontent.com/54677832/202251184-c9290abb-53cc-4bfe-94c0-da6954fef2fb.png)

When I fixed the error in the _regex_, it finally _saved_ the pattern in my profile.

⚠️ Still, I wasn't able to add a **Text** to test the new regex: when I add it, then it wouldn't save (again, and the problem persist after _logout_ and _login_, and on different browsers - Chrome, Firefox, Edge).
**The error is the same as reported when trying to save an invalid regex pattern.**
This is the **Text** I'm trying to add to test the regex:
```
./../../XSD/VWXML_Structure.xsd

./../../XSD/VWXML_Behavior.xsd

./../../XML/ProjectProperties.xml
```
The _regex_ I saved in _my patterns_ is this one: `([A-Z\.\/]+)\/([A-Za-z_\.]+)`.

Thank you in advance for your support.

**Comment by gskinner** [comment]
Thanks for the report. At a quick glance, this is generating a server error:
`Failed to load resource: the server responded with a status of 418 ()`

We will look into why that's happening. It could be related to our recent server move.

**Comment by gskinner** [comment]
Quick update. Looks like it is related to the new hosting. We're continuing to investigate.

**Comment by gskinner** [comment]
This should be fixed now. It was an enhanced security setting on the new host.
