### ISSUE TITLE
The page isn’t redirecting properly

### ISSUE THREAD

**Issue by Lonniebiz** [gskinner/regexr#488]
I just went to https://regexr.com/ and got this error in Firefox:
![2023-01-19_00-42](https://user-images.githubusercontent.com/151919/213373547-caee9ead-3ec1-48ea-bd39-963967ead813.png)

And this error using Chromium:
![2023-01-19_00-42_1](https://user-images.githubusercontent.com/151919/213373552-d12946a1-1b14-4d57-ab32-4b529460c7fd.png)

**Comment by simon-glitch** [comment]
**Yeah; my computer tells me that the site redirected too many times, and now I can't use it AT ALL!**

**Comment by zhekoff316** [comment]
Yesterday, there was an "Expired SSL certificate" warning, so it might be connected as well.

**Comment by mommy742** [comment]
[
![Screenshot 2023-01-19 091715](https://user-images.githubusercontent.com/16270026/213480544-b41643ca-9e1b-4a02-b00e-55e198bb38b8.png)
](url)


same for me.

**Comment by gskinner** [comment]
This should be solved now. Another issue with DreamHost trying to autoupdate the host-level cert. We've made additional changes that should resolve it going forward.

**Comment by Lonniebiz** [comment]
I confirm:
![2023-03-15_06-07](https://user-images.githubusercontent.com/151919/225291727-3664edcb-3a9c-41df-bd1f-8811ddc1487b.png)
