### ISSUE TITLE
Mixed content warning when self-hosting over SSL

### ISSUE THREAD

**Issue by TheFiZi** [gskinner/regexr#51]
When self-hosting and using SSL Firefox throws a mixed content warning requiring user interaction for regexr to fully load.

Line 81 in index.html change from:
   <script src="http://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js">
to
   <script src="https://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js">
gets rid of the mixed content warning.

Not sure if you want to change this or add some logic to detect if SSL is being used and automatically use the https version of Google APIs instead of http.

**Comment by Nightfirecat** [comment]
Of note, protocol-relative URLs are now considered an anti-pattern; it's always safe to load resources over HTTPS, even when loading from an HTTP source, but the inverse is not true. The original fix (just using the HTTPS link) is a better solution.

**Comment by gskinner** [comment]
We are self-hosting fonts now, so this should be a non-issue.
