### ISSUE TITLE
Global indicator not working in tests

### ISSUE THREAD

**Issue by myverdict** [gskinner/regexr#513]
My regex pattern is: `/[^a-zA-Z0-9 ]+/g`

Text: "a confusing /:sentence:/[ this is not!!!!!!!~"

1. When I put the above text in the "Text" box, the expression works correctly.

![text](https://github.com/gskinner/regexr/assets/26878263/8eaafbd3-2bee-4330-bad3-b889c93d2238)

2. When I put the above text in the "Tests", the test does not seem to work properly. The global indicator does not get implemented. 

![2](https://github.com/gskinner/regexr/assets/26878263/959837b1-eec2-4db1-b041-173b1aadbf72)

QUESTION: Is the above image the intended behavior when testing, i.e., the global indicator does not get implemented in tests?

Setting to "MATCH FULL" fails the test, please see image below:

![3](https://github.com/gskinner/regexr/assets/26878263/b2c60266-e644-4b03-94e3-caf32dff294e)

QUESTION: Not sure if I have to use "MATCH ANY" or "MATCH FULL" here as either way the global indicator does not seem to get applied to the test case.

**Comment by gskinner** [comment]
This is expected behaviour. The test is to "match any", so as soon as a match is found, the test is successful. It's optimized to not waste additional resources to find further matches because the pass/fail is already determined.
