### ISSUE TITLE
Feature Request: insert RegExp/Terms via URL

### ISSUE THREAD

**Issue by atk** [gskinner/regexr#55]
I'd like to autolink to RegExr with RegExp/Testing Terms pre-filled via URL parameters, but there's no API available, only one to save and share, which will not work automatically.

**Comment by ChrisCinelli** [comment]
Very interested in this.

**Comment by mikechamberlain** [comment]
Yes please.

**Comment by gskinner** [comment]
This has been added to v3.0, in the form:
http://regexr.com?expression=foo&text=bar

It will also have support for Tool, just finalizing the naming for the tool input. Will leave this open until we launch v3.

**Comment by gskinner** [comment]
This has been added in v3.0 in the form:
http://regexr.com?expression=foo&text=bar&tool=replace&input=replstr

It is also documented in Help, under "Query string support"

**Comment by shreyasminocha** [comment]
Does this support the new tests feature? 

If not, would implementing that be feasible?
