### ISSUE TITLE
could switch googleapis static files to other cdn?

### ISSUE THREAD

**Issue by callmez** [gskinner/regexr#57]
hello 
i am developer from china. you guys are doing great job, i love your project very much.
as you know.    in china there is some country reason can’t use google services very well . 
so  i  will wait when i visit http://regexr.com for to long..
this is very sad.
could please switch other cdn or has some solution for this.  
thanks  very much.

**Comment by wdamien** [comment]
Thanks for all the feedback here! This should be resolved with the latest version (live at www.regexr.com) The site still uses google fonts, but has much better fallback support when fonts fail to load. We might look into future support for either self hosted or using a service like jsDelivr, but for now the default fonts will work if, for whatever reason, google fonts fail to load.

@callmez  Please to re-open this if regexr still doesn't load for you.
