### ISSUE TITLE
Capturing Groups

### ISSUE THREAD

**Issue by pribilinskiy** [gskinner/regexr#6]
v1 had a convenient "overview" section in the bottom where the capturing groups could be observed in a list
hopefully it is planned for v2 and will be as sophisticated as the HiFi Regex Tester table output
http://www.gethifi.com/tools/regex

![faymbty 1](https://cloud.githubusercontent.com/assets/3078595/2548690/0899e700-b667-11e3-837d-f7523cc84abc.png)

**Comment by bradisbell** [comment]
Even if you can't associate the captured data with the capture group, it would be helpful just to output the raw result anyway... the equivalent of `console.log()` on the match.

**Comment by gskinner** [comment]
I'm actually working on a Details tool at this very moment that will show the full text of a selected match and each group. Does it sound like that will do what you need?

**Comment by bradisbell** [comment]
Yes, exactly!

**Comment by gskinner** [comment]
Details shipped in v2.1, so I'm closing this rather belatedly. As a quick note, the Details tool in v3.0 is more robust, especially when using the PCRE engine (which provides position info for groups).

**Comment by eromoe** [comment]
But color still not show now ? Only way to see group is using Detail tools?
