### ISSUE TITLE
Minor Glitch in Chrome

### ISSUE THREAD

**Issue by CoffinBound** [gskinner/regexr#65]
Just wanted to pass along something I noted while using the web version. I experienced this only in Google Chrome. Firefox and IE appeared to display properly. Open the www.regexr.com site and remove the \w+ from the expression. It incorrectly highlights the following strings of text; "&" symbol in the string Save & Share - and the string ", or watch the video " in the last sentence of that paragraph.Technically, they are still highlighted without changing the expression, but this is what caused me to notice the bug.

**Comment by gskinner** [comment]
I believe this was resolved, but never closed.
