### ISSUE TITLE
Option to show 'Symbols' for non-visible characters in editor

### ISSUE THREAD

**Issue by CreepyGnome** [gskinner/regexr#68]
It would be very useful if there was a way to show the symbols that represent the various non-visible characters.  Could be just buttons above Text edit area in that grayish zone, with something like "Show White Space and Tab", "Show End of Lines" and "Show All Characters" similar to Notepad++ and other popular text editors.

As I can write a regex with Regexr that will match on the non-visible characters and the match count will show the number of matches, however I have no visual indication of what it matched on, just that it did. This makes it difficult to verify if the non-visible character matching is working as expected or not.

Thanks, for the great web based tool, I use it for all my complex Regex I need to validate and work out.

**Comment by gskinner** [comment]
This is coming in v3.0, with the exception of line breaks, due to some limitations in CodeMirror that I'm hoping to work around in the future.

**Comment by gskinner** [comment]
This is done in v3. It also displays line breaks, but unfortunately can't highlight them yet. Tracked in #206
