### ISSUE TITLE
Maybe a generator?

### ISSUE THREAD

**Issue by MHM5000** [gskinner/regexr#69]
If the app was able to generate examples from a Regex,
this app would be in more use...

**Comment by gskinner** [comment]
Can you provide examples of the input / output of this? It seems like it would just generate noise in most cases.

For example, `\W*` could generate anything from an empty string, to a 50,000 string of completely unintelligible characters. The top example from the linked search above gives super weird results for that input (it REALLY loves angle brackets and returns a max string length of 3).

Feel free to reopen this with a use case.
