### ISSUE TITLE
Add support for new ES6 features 

### ISSUE THREAD

**Issue by wdamien** [gskinner/regexr#75]
ES6 adds 2 new flags to RegExp (y and u) (more info: https://mathiasbynens.be/notes/es6-unicode-regex and https://docs.webplatform.org/wiki/javascript/RegExp/sticky). They're not widely supported yet, but would be a nice to add for browsers that support them.  Related to #15

**Comment by mklemarczyk** [comment]
ES6 is supported in flash only.

**Comment by arthurvr** [comment]
> ES6 is supported in Adobe flash only.

**Comment by mklemarczyk** [comment]
First, ES6 has not been released yet. Second, none of web browsers support ES6 right now in production mode. ES is not a JavaScript. JavaScript is an implementation of ECMAScript.

**Comment by gskinner** [comment]
This is coming in v3.0

**Comment by gskinner** [comment]
Added `u` & `y` in v3.0. The `y` flag doesn't really do anything in context of the tool though.
