### ISSUE TITLE
Color Coding

### ISSUE THREAD

**Issue by anubisthejackle** [gskinner/regexr#79]
It'd be great if the different capturing and non-capturing groups were color coded in the text area.

**Comment by gskinner** [comment]
See: https://github.com/gskinner/regexr/issues/6

**Comment by kael** [comment]
I'd have a feature request, but not sure if I'm missing something, if I should open a new issue or not.

Would it be possible to use different colors in the expression panel area instead of shades of green, one color per group ? That'd be nice when capturing more than 10 groups and sub-groups.
