### ISSUE TITLE
Expiration of shared community links

### ISSUE THREAD

**Issue by KyleMit** [gskinner/regexr#84]
Here's a shared link I just made today (2/26/15) which appears to be working fine:

http://regexr.com/3agn8

But here's a shared link I created 3 months ago on 11/25/14 which does not load the previously saved content, but the regular homepage instead:

http://regexr.com/39vao

I get the following error message in my console:

>     Unhandled promise rejection 
>       [[PromiseStatus]]: "rejected"
>       [[PromiseValue]]: SyntaxError: Unexpected end of input 

Tested in Chrome 40, FF34, IE11	

Here's the code causing the issue:

```
ServerModel.getPatternByID(t).then(function (e) {
    ExpressionModel.setLastSave(e);
    var i = $.parsePattern(e.pattern);
    n.docView.setState(JSON.parse(e.state)), n.docView.populateAll(i.ex, i.flags, e.content, e.replace)
}, function () {
    BrowserHistory.go()
})
```

Specifically with `JSON.parse(e.state)`

The old item doesn't come back with anything in the state field so the pasing fails:

![old vs new](http://i.imgur.com/w6pujna.png)

Interestingly, if you go to the Community section and search for `KyleMit` and then click on the entry for **`Query String Finder`**, it will pull up the correct contents and update the URL to the one above.  Yay!  That data still exists somewhere.  But if you go into the address bar and hit enter, the page will go back to the homepage.

**Update**:

This might have been fixed by [Fixed displaying substitution panel when value is empty.](https://github.com/gskinner/regexr/commit/6913ebdb243a118f100137b69bc214235909ab41)

**Comment by wdamien** [comment]
Thanks for the report! A fix has been pushed to regexr.com. Your first visit might require a refresh to get the latest source.

**Comment by KyleMit** [comment]
Thanks!  Works great!
