### ISSUE TITLE
Match ASCII control characters

### ISSUE THREAD

**Issue by zigfreid5** [gskinner/regexr#85]
I need to match control characters found in ascii characters 0-33. Is there a way to use these in the text panel?

**Comment by GodLesZ** [comment]
AFAIK where are matched.
Quick test: http://regexr.com/3akkp

As shown, they are matched (\cJ for newline), but the text-match tooltip doesnt show them

**Comment by gskinner** [comment]
Showing invisible characters is on the list for v3.0, but they likely still won't show up in the tooltip. Maybe in v3.1.

**Comment by gskinner** [comment]
Tracking in #205
