### ISSUE TITLE
.NET Regex

### ISSUE THREAD

**Issue by weitzhandler** [gskinner/regexr#87]
Hi,
First of all let me thank you from the bottom of my heart for this awesome useful tool!

I don't know if there are so many major differences between the JS Regex and the .NET one.
Anyway [here](http://regexr.com/3ak0n) is one:

    ^(?<countryCode>[\+][1-9]{1}[0-9]{0,2}\s)?(?<areaCode>0?[1-9]\d{0,4})(?<number>\s[1-9][\d]{5,12})(?<extension>\sx\d{0,4})?$

Capturing group names in .NET are enclosed with (`?<name>groupToken)` or `(?'name'groupToken)`, this is not recognized by the regexr validator, please implement a checkbox for users to specify that they're using .NET regex.

Best

**Comment by wdamien** [comment]
Other syntax support has been planned, checkout #32
