### ISSUE TITLE
Issue with Polish chars and word boundary

### ISSUE THREAD

**Issue by marsjaninzmarsa** [gskinner/regexr#90]
http://regexr.com/3arrj

(`ę`, `ą`, `ź`, `ż`, `ś`, `ł`, `ó`, `ć`, `ń` is not a punctuation, not a whitespace either).

**Comment by wdamien** [comment]
Javascript RegExp currently has poor support for multilingual characters, @see #75. Until ES6 is fully supported by browsers you can use a unicode character range, ex:
```
[\u0104-\u017b]/g
```
http://regexr.com/3artr

**Comment by gskinner** [comment]
We should update the reference to be more clear about this though. Reopening for that reason.

**Comment by gskinner** [comment]
Addressed in the Reference in v3.0

**Comment by gskinner** [comment]
Addressed in v3.0
