### ISSUE TITLE
Add help icons to Replace & List

### ISSUE THREAD

**Issue by weitzhandler** [gskinner/regexr#92]
Hi,

I use RegExr mainly as a productivity and sharing tool, but also a lot as a learning tool. The comprehensive and yet summarized cheatsheet and information box in the left is very convenient to learn from and remember.

Anyway, there is barely information on how to use the substitutions field. Please add some tutorials/informations on this, and make it easier to work with complex substitutions.

**Comment by lannymcnie** [comment]
There is some documentation under "Reference > Substitution" which should suffice. This section has also been totally revamped.
![screen shot 2016-05-27 at 10 43 39 am](https://cloud.githubusercontent.com/assets/590731/15614814/01b51d96-23f8-11e6-9afd-702c81fad5bc.png)

**Comment by gskinner** [comment]
v3.0 will have a question mark icon in the Replace tool, with a link to Help content.

**Comment by gskinner** [comment]
Still need to add the help icon.

**Comment by gskinner** [comment]
This has been added locally.
