### ISSUE TITLE
Case Insensitivity (?i)

### ISSUE THREAD

**Issue by TekBoi** [gskinner/regexr#93]
The tool does not support case-insensitivity.

**Comment by gskinner** [comment]
js regex does not support the ?i operator. However you can use the /i flag (applies to the whole expression).

**Comment by Serhiy-Shekhovtsov** [comment]
Didn't work for me today. 
![image](https://cloud.githubusercontent.com/assets/607527/19562429/f47d79ce-96e4-11e6-8a0b-0c545b582c7f.png)

**Comment by Serhiy-Shekhovtsov** [comment]
Ok, there is an option for this now. I had to click **flags** button on the right.

**Comment by gskinner** [comment]
Alternatively you can click the flags to the immediate right of the expression (ie `/g`) which will open the flags menu.

RegExr also supports pasting a full expression in that has flags.

**Comment by Serhiy-Shekhovtsov** [comment]
Pasting expression with flags didn't work for me.

**Comment by wdamien** [comment]
@Serhiy-Shekhovtsov Can you provide some details on how your testing the paste with flags?  I just tested using Chrome 54 on a Mac and the flags paste fine for me. So it could be a browser specific bug.

**Comment by Serhiy-Shekhovtsov** [comment]
You can see a screenshot above, and here comes an other one:
![image](https://cloud.githubusercontent.com/assets/607527/19575156/e177450e-9715-11e6-8517-580f1cbeb67c.png)
I am using Chrome version **53.0.2785.143** m, on Windows 7 x64

**Comment by gskinner** [comment]
Hmm. I tested on the same version of Chrome on Mac (53.0.2785.143), and it worked as expected. I'll try to test a bit later on Windows, though I only have Win10.

**Comment by gskinner** [comment]
Just tested in Chrome 52 on Win10 (doesn't want to update to 53 for some reason), and it worked as expected. Maybe this is Win7 specific? Is there anything at all unusual you can think of in how you're pasting the expression? I tested right click > paste, and ctrl-v.

**Comment by Serhiy-Shekhovtsov** [comment]
Sorry, man, I didn't know you mean pasting literally and tried typing :( 
The pasting works perfectly.

**Comment by gskinner** [comment]
No worries, glad we were able to figure it out. :)
