### ISSUE TITLE
Support named capture groups

### ISSUE THREAD

**Issue by rfkrocktk** [gskinner/regexr#95]
In more than a few languages, named capture groups are supported with:

```
/\b(?P<package>[-_0-9a-z]+)-(?P<version>\d+)\.(?P<arch>[_0-9a-z]+)\.(rpm)\b/ig
```

This allows me to get the package name with a named group rather than a one-indexed one. 

Can you add support for named capture groups to RegExr?

**Comment by lannymcnie** [comment]
Currently, RegExr only supports JavaScript RegExp, which does not have support for named capture groups.

**Comment by wdamien** [comment]
Please see #32 for more details.
