### ISSUE TITLE
ZeroClipboard error when running grunt build

### ISSUE THREAD

**Issue by TheFiZi** [gskinner/regexr#98]
Just updated to the latest source, ran 'npm install' and then 'grunt build' and got the following:

	sa_regexer@micro ~/regexr $ grunt build
	Running "clean:build" (clean) task
	>> 0 paths cleaned.

	Running "sass:build" (sass) task

	Running "browserify:build" (browserify) task
	>> Error: Cannot find module 'ZeroClipboard' from '/data/apps/sa_regexer/regexr/js'
	Warning: Error running grunt-browserify. Use --force to continue.

	Aborted due to warnings.

ZeroClipboard and grunt-browserfy are installed

	sa_regexer@micro ~/regexr $ npm install zeroclipboard
	npm WARN package.json placeholders.js@3.0.2 No repository field.
	npm http GET https://registry.npmjs.org/zeroclipboard
	npm http 304 https://registry.npmjs.org/zeroclipboard
	zeroclipboard@2.2.0 node_modules/zeroclipboard

	sa_regexer@micro ~/regexr $ npm install grunt-browserify
	......
	grunt-browserify@3.8.0 node_modules/grunt-browserify
	├── async@0.9.2
	├── resolve@1.1.6
	├── glob@5.0.10 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
	├── lodash@3.9.3
	└── watchify@3.2.1 (defined@1.0.0, xtend@4.0.0, outpipe@1.1.1, through2@0.6.5, chokidar@1.0.2)
	sa_regexer@micro ~/regexr $

**Comment by wdamien** [comment]
@TheFiZi I just tried doing fresh install of my node_modules and was able to run ```grunt``` and ```grunt build``` without any issues. Can you make sure your local modules are all installed correctly?  Try deleting your node_modules and run a fresh  ```npm install```.  If that doesn't work can you send over your ```node -v``` (I'm testing using 0.12.4).

**Comment by TheFiZi** [comment]
rm -rf node_modules
    npm install

No errors

Same error running grunt build.

I'm using Grunt v0.4.5 and Node v0.10.33

I'll try upgrading node.

**Comment by TheFiZi** [comment]
No dice with node 0.12.4, grunt 0.4.5, ruby 2.1.6

	sa_regexer@micro ~/regexr $ rm -rf node_modules

	sa_regexer@micro ~/regexr $ npm install
	npm WARN package.json RegExr@2.0.0 No license field.
	npm WARN optional dep failed, continuing fsevents@0.3.6
	npm WARN optional dep failed, continuing fsevents@0.3.6

	> ws@0.5.0 install /data/apps/sa_regexer/regexr/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws
	> (node-gyp rebuild 2> builderror.log) || (exit 0)

	make: Entering directory `/data/apps/sa_regexer/regexr/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
	  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
	  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
	  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
	  COPY Release/bufferutil.node
	  CXX(target) Release/obj.target/validation/src/validation.o
	  SOLINK_MODULE(target) Release/obj.target/validation.node
	  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
	  COPY Release/validation.node
	make: Leaving directory `/data/apps/sa_regexer/regexr/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'

	> ws@0.4.31 install /data/apps/sa_regexer/regexr/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
	> (node-gyp rebuild 2> builderror.log) || (exit 0)

	make: Entering directory `/data/apps/sa_regexer/regexr/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
	  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
	make: Leaving directory `/data/apps/sa_regexer/regexr/node_modules/grunt-browser-sync/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
	classlist-polyfill@1.0.1 node_modules/classlist-polyfill

	store@1.3.17 node_modules/store

	placeholders.js@3.0.2 node_modules/placeholders.js

	grunt-contrib-clean@0.6.0 node_modules/grunt-contrib-clean
	└── rimraf@2.2.8

	grunt-contrib-copy@0.8.0 node_modules/grunt-contrib-copy
	├── file-sync-cmp@0.1.1
	└── chalk@0.5.1 (escape-string-regexp@1.0.3, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)

	grunt-contrib-sass@0.9.2 node_modules/grunt-contrib-sass
	├── dargs@4.0.1 (number-is-nan@1.0.0)
	├── async@0.9.2
	├── chalk@0.5.1 (escape-string-regexp@1.0.3, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
	├── cross-spawn@0.2.9 (lru-cache@2.6.4)
	└── which@1.1.1 (is-absolute@0.1.7)

	zeroclipboard@2.2.0 node_modules/zeroclipboard

	grunt-contrib-htmlmin@0.4.0 node_modules/grunt-contrib-htmlmin
	├── chalk@0.5.1 (escape-string-regexp@1.0.3, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
	└── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.1.0)

	es6-promise@2.1.1 node_modules/es6-promise

	uglify-js@2.4.23 node_modules/uglify-js
	├── uglify-to-browserify@1.0.2
	├── async@0.2.10
	├── yargs@3.5.4 (camelcase@1.1.0, decamelize@1.0.0, window-size@0.1.0, wordwrap@0.0.2)
	└── source-map@0.1.34 (amdefine@0.1.0)

	html-minifier@0.7.2 node_modules/html-minifier
	├── relateurl@0.2.6
	├── change-case@2.3.0 (pascal-case@1.1.1, param-case@1.1.1, title-case@1.1.1, snake-case@1.1.1, dot-case@1.1.1, path-case@1.1.1, is-upper-case@1.1.1, lower-case-first@1.0.0, upper-case-first@1.1.1, is-lower-case@1.1.1, constant-case@1.1.1, upper-case@1.1.2, camel-case@1.1.2, swap-case@1.1.1, lower-case@1.1.2, sentence-case@1.1.2)
	├── concat-stream@1.4.8 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13)
	├── cli@0.6.6 (exit@0.1.2, glob@3.2.11)
	└── clean-css@3.1.9 (commander@2.6.0, source-map@0.1.43)

	grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch
	├── async@0.2.10
	├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
	├── gaze@0.5.1 (globule@0.1.0)
	└── lodash@2.4.2

	grunt-contrib-connect@0.10.1 node_modules/grunt-contrib-connect
	├── opn@1.0.2
	├── connect-livereload@0.5.3
	├── async@0.9.2
	├── portscanner@1.0.0 (async@0.1.15)
	└── connect@2.29.2 (vhost@3.0.0, response-time@2.3.1, content-type@1.0.1, on-headers@1.0.0, parseurl@1.3.0, utils-merge@1.0.0, cookie-signature@1.0.6, cookie@0.1.2, fresh@0.2.4, pause@0.0.1, basic-auth-connect@1.0.0, bytes@1.0.0, depd@1.0.1, cookie-parser@1.3.5, qs@2.4.2, http-errors@1.3.1, method-override@2.3.3, debug@2.2.0, connect-timeout@1.6.2, morgan@1.5.3, finalhandler@0.3.6, serve-favicon@2.2.1, express-session@1.10.4, csurf@1.7.0, type-is@1.6.2, multiparty@3.3.2, serve-static@1.9.3, compression@1.4.4, errorhandler@1.3.6, body-parser@1.12.4, serve-index@1.6.4)

	grunt@0.4.5 node_modules/grunt
	├── which@1.0.9
	├── dateformat@1.0.2-1.2.3
	├── eventemitter2@0.4.14
	├── getobject@0.1.0
	├── rimraf@2.2.8
	├── colors@0.6.2
	├── hooker@0.2.3
	├── async@0.1.22
	├── grunt-legacy-util@0.2.0
	├── exit@0.1.2
	├── nopt@1.0.10 (abbrev@1.0.7)
	├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.4)
	├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
	├── lodash@0.9.2
	├── coffee-script@1.3.3
	├── underscore.string@2.2.1
	├── iconv-lite@0.2.11
	├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)
	├── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)
	└── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)

	grunt-browserify@3.8.0 node_modules/grunt-browserify
	├── async@0.9.2
	├── resolve@1.1.6
	├── glob@5.0.10 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
	├── watchify@3.2.1 (defined@1.0.0, xtend@4.0.0, through2@0.6.5, outpipe@1.1.1, chokidar@1.0.2)
	└── lodash@3.9.3

	grunt-contrib-uglify@0.9.1 node_modules/grunt-contrib-uglify
	├── uri-path@0.0.2
	├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, has-ansi@1.0.3, strip-ansi@2.0.1)
	├── maxmin@1.1.0 (figures@1.3.5, pretty-bytes@1.0.4, gzip-size@1.0.0)
	└── lodash@3.9.3

	browserify-shim@3.8.7 node_modules/browserify-shim
	├── through@2.3.7
	├── mothership@0.2.0 (find-parent-dir@0.3.0)
	├── resolve@0.6.3
	├── exposify@0.2.0 (through2@0.4.2, transformify@0.1.2, detective@2.3.0)
	└── rename-function-calls@0.1.1 (detective@3.1.0)

	browserify@10.2.3 node_modules/browserify
	├── https-browserify@0.0.0
	├── htmlescape@1.1.0
	├── tty-browserify@0.0.0
	├── builtins@0.0.7
	├── constants-browserify@0.0.1
	├── path-browserify@0.0.0
	├── os-browserify@0.1.2
	├── isarray@0.0.1
	├── inherits@2.0.1
	├── through2@1.1.1
	├── process@0.11.1
	├── string_decoder@0.10.31
	├── stream-browserify@1.0.0
	├── domain-browser@1.1.4
	├── shell-quote@0.0.1
	├── has@1.0.0
	├── defined@1.0.0
	├── commondir@0.0.1
	├── punycode@1.3.2
	├── xtend@4.0.0
	├── duplexer2@0.0.2
	├── deep-equal@1.0.0
	├── querystring-es3@0.2.1
	├── assert@1.3.0
	├── timers-browserify@1.4.1
	├── deps-sort@1.3.9
	├── util@0.10.3
	├── events@1.0.2
	├── vm-browserify@0.0.4 (indexof@0.0.1)
	├── parents@1.0.1 (path-platform@0.11.15)
	├── read-only-stream@1.1.1 (readable-wrap@1.0.0)
	├── console-browserify@1.1.0 (date-now@0.1.4)
	├── subarg@1.0.0 (minimist@1.1.1)
	├── concat-stream@1.4.8 (typedarray@0.0.6)
	├── http-browserify@1.7.0 (Base64@0.2.1)
	├── readable-stream@1.1.13 (core-util-is@1.0.1)
	├── shasum@1.0.1 (sha.js@2.3.6, json-stable-stringify@0.0.1)
	├── url@0.10.3 (querystring@0.2.0)
	├── labeled-stream-splicer@1.0.2 (stream-splicer@1.3.1)
	├── resolve@1.1.6
	├── browser-resolve@1.9.0
	├── buffer@3.2.2 (ieee754@1.1.5, is-array@1.0.1, base64-js@0.0.8)
	├── glob@4.5.3 (once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
	├── JSONStream@1.0.4 (through@2.3.7, jsonparse@1.0.0)
	├── syntax-error@1.1.4 (acorn@1.2.2)
	├── crypto-browserify@3.9.14 (randombytes@2.0.1, create-hmac@1.1.3, pbkdf2@3.0.4, create-hash@1.1.1, diffie-hellman@3.0.2, browserify-aes@1.0.1, create-ecdh@2.0.1, browserify-sign@3.0.2, public-encrypt@2.0.1)
	├── browser-pack@5.0.1 (umd@3.0.1, combine-source-map@0.6.1)
	├── browserify-zlib@0.1.4 (pako@0.2.6)
	├── insert-module-globals@6.5.0 (combine-source-map@0.3.0, lexical-scope@1.1.1)
	└── module-deps@3.8.0 (stream-combiner2@1.0.2, detective@4.1.0)

	codemirror@5.3.0 node_modules/codemirror

	inline-source@4.0.0 node_modules/inline-source
	├── htmlparser2@3.8.2 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
	├── uglify-js@2.4.21 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)
	├── svgo@0.5.2 (whet.extend@0.9.9, colors@1.1.0, mkdirp@0.5.1, coa@1.0.1, sax@1.1.1, js-yaml@3.3.1)
	├── lodash@3.8.0
	└── csso@1.3.11

	grunt-browser-sync@2.1.3 node_modules/grunt-browser-sync
	└── browser-sync@2.7.6 (async-each-series@0.1.1, longest@1.0.1, query-string@2.2.0, emitter-steward@0.0.1, ucfirst@0.0.1, opn@1.0.2, dev-ip@1.0.1, pad-left@1.0.2, ua-parser-js@0.7.7, meow@3.1.0, portscanner@1.0.0, connect@3.3.5, browser-sync-client@2.0.2, serve-static@1.9.3, foxy@11.0.0, immutable@3.7.3, resp-modifier@3.1.2, anymatch@1.3.0, chokidar@1.0.2, serve-index@1.6.4, easy-extender@2.3.1, eazy-logger@2.1.2, localtunnel@1.5.1, lodash@3.9.3, browser-sync-ui@0.5.9, socket.io@1.3.5)



	sa_regexer@micro ~/regexr $ grunt build
	Running "clean:build" (clean) task
	>> 0 paths cleaned.

	Running "sass:build" (sass) task

	Running "browserify:build" (browserify) task
	>> Error: Cannot find module 'ZeroClipboard' from '/data/apps/sa_regexer/regexr/js'
	Warning: Error running grunt-browserify. Use --force to continue.

	Aborted due to warnings.

**Comment by TheFiZi** [comment]
Fixed it

	cd node_modules/
	ln -s zeroclipboard ZeroClipboard

Casing :)

**Comment by wdamien** [comment]
Nice find. I pushed a code fix for case sensitive systems.
