### ISSUE TITLE
Ability to change default listening port

### ISSUE THREAD

**Issue by TheFiZi** [gskinner/regexr#99]
I figured this out at one point but can't remember how I changed the listening port.

Would be nice if there was a config.js or something that allowed for changing the default listening port.

**Comment by wdamien** [comment]
Whats the reason for needing a custom port?  broswerSync will just find an open port and use it.  Closing for now, unless valid reason comes up to require configuring a custom port.

**Comment by TheFiZi** [comment]
I run multiple services on a server and proxy regexer behind Apache so I can access it on port 80/443 with all of my other web services.

If I install a service down the line that runs on 8000 and then restart regexer and it grabs port 8001 that breaks my proxy config. Rinse/repeat.

If I can specify a port I know will not be used (for example 65515) I am guaranteed it will always be that port.

**Comment by TheFiZi** [comment]
So I previously had a tweak that was working for changing the default port. Seems the latest build doesn't allow me to do it anymore.

Normally I think I just changed this line in gulpfile.js

	gulp.task('open-build', function () {
	        gulp.src(__filename)
	                .pipe(open({uri: 'http://localhost:65515'}));
	});

So instead I'm trying to figure out how to pass parameters to browser-sync:

	gulp.task('browser-sync', function () {
	        return browserSync(
	                {
	                        open: "local",
	                        port: 65515,
	                        proxy: "localhost:65515",
	                        ui: {
	                            port: 65515
	                        },
	                        server: {
	                                baseDir: "./build/"
	                        },
	                        files: "./build/**"
	                });
	});

None of which appear to be working.

Sorry I'm not a dev, just a sysadmin. I'd appreciate any help or the ability to specify a custom port :)

**Comment by gskinner** [comment]
This is one of those features we'd accept a pull request for, but it's unlikely to make it onto our dev list. I'm going to leave it open for a bit, because I'm willing to take a quick look once v3.0 launches.

**Comment by gskinner** [comment]
v3.0 is currently not open source, so closing this for now.
